force-app/main/default/objects/Case/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <formula>Invoice__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Schindler_Invoice_History__c.field-meta.xml
<CustomField>
    <fullName>Schindler_Invoice_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Schindler_Invoice_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Notification master</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Billing_Id__c.field-meta.xml
<CustomField>
    <fullName>Billing_Id__c</fullName>
    <label>Billing Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <inlineHelpText>For TK, equivalent to Customer #</inlineHelpText>
    <label>Contract</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>For TK, refer to Resolution Summary.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Duns_Number__c</fullName>
    <label>Duns Number</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Federal_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id__c</fullName>
    <label>Federal Tax Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Field_Contact__c.field-meta.xml
<CustomField>
    <fullName>Field_Contact__c</fullName>
    <label>Field Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number - not used</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Labor__c.field-meta.xml
<CustomField>
    <fullName>Labor__c</fullName>
    <label>Labor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Local_Office__c.field-meta.xml
<CustomField>
    <fullName>Local_Office__c</fullName>
    <label>Local Office</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <inlineHelpText>For TK, it is SR #</inlineHelpText>
    <label>Order No</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <label>Payer</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Problem_Count__c.field-meta.xml
<CustomField>
    <fullName>Problem_Count__c</fullName>
    <label>Problem Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Problems__c.field-meta.xml
<CustomField>
    <fullName>Problems__c</fullName>
    <label>Problems</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Remit_To__c.field-meta.xml
<CustomField>
    <fullName>Remit_To__c</fullName>
    <label>Remit To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Contact__c</fullName>
    <label>Sales Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Subtotal</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/invoiceFormController.cls
public without sharing class invoiceFormController {

  @AuraEnabled
  public static string SaveHistoryRec(
    String billTo,
    String billingId,
    String contract,
    String contentVersionId,
    String description,
    String dunsNumber,
    String expenses,
    String fax,
    String federalTaxId,
    String fieldContact,
    String historyId,
    String invoiceDate,
    String invoiceNumber,
    String invoiceTotal,
    String labor,
    String localOffice,
    String notification,
    String orderNo,
    String orderType,
    String payer,
    String remitTo,
    String salesContact,
    String serviceLocation,
    String subtotal,
    String tax,
    String telephone,
    String problems,
    String problemCount) {

    Integer problemCountInt=0;
    Decimal expensesDec=0,invoiceTotalDec=0,laborDec=0,subTotalDec=0,taxDec=0;        
    String expensesStr='',invoiceTotalStr='',laborStr='',subtotalStr='',taxStr='';

    if(!String.isBlank(problemCount)) {
      problemCountInt = Integer.valueOf(problemCount);
    }

    // removeStart('$') is only required for invoiceTotal, but applying it to all in case format of numbers change in future.  If no $ is present, no change.  Same for replaceAll.
    if(!String.isBlank(expenses)) {
      expensesStr     = expenses.removeStart('$').replaceAll(',','');
      expensesStr     = expensesStr.replaceAll(' ','');
      expensesDec     = Decimal.valueOf(expensesStr);
    }
    
    if(!String.isBlank(invoiceTotal)) {
      invoiceTotalStr = invoiceTotal.removeStart('$').replaceAll(',','');
      invoiceTotalStr = invoiceTotalStr.replaceAll(' ','');
      invoiceTotalDec = Decimal.valueOf(invoiceTotalStr);
    } 
    if(!String.isBlank(labor)) {
      laborStr        = labor.removeStart('$').replaceAll(',','');
      laborStr        = laborStr.replaceAll(' ','');
      laborDec        = Decimal.valueOf(laborStr);
    }
    if(!String.isBlank(subtotal)) {
      subtotalStr     = subtotal.removeStart('$').replaceAll(',','');
      subtotalStr     = subtotalStr.replaceAll(' ','');
      subTotalDec     = Decimal.valueOf(subtotalStr);
    } 
    if(!String.isBlank(tax)) {
      taxStr          = tax.removeStart('$').replaceAll(',','');
      taxStr          = taxStr.replaceAll(' ','');
      taxDec          = Decimal.valueOf(taxStr);
    }

    Date invoice_Date = null;
    if(!String.isBlank(tax)) {
      String[] invoiceDateArray = invoiceDate.split('/');
      Integer  invoiceDateMonth = Integer.valueOf(invoiceDateArray[0]);
      Integer  invoiceDateDay   = Integer.valueOf(invoiceDateArray[1]);
      Integer  invoiceDateYear  = Integer.valueOf(invoiceDateArray[2]);
      invoice_Date = Date.newinstance(invoiceDateYear, invoiceDateMonth, invoiceDateDay);
    } 

  /*
    System.debug('historyId: ' + historyId);
    System.debug(invoice_Date);
    System.debug(notification);

    System.debug(localOffice);
    System.debug(serviceLocation);
    System.debug(billTo);
    System.debug(billingId);
    System.debug(dunsNumber);
    System.debug(contract);
    System.debug(orderNo);
    System.debug(orderType);
    System.debug(telephone);
    System.debug(fax);
    System.debug(federalTaxId);
    System.debug(salesContact);
    System.debug(fieldContact);
    System.debug(invoiceNumber);
    System.debug(description);
    System.debug('laborStr        ' + laborStr);
    System.debug('expensesStr     ' + expensesStr);
    System.debug('taxStr          ' + taxStr);
    System.debug('subtotalStr     ' + subtotalStr);
    System.debug('invoiceTotalStr ' + invoiceTotalStr);
    System.debug('remit To '        + remitTo);
    System.debug(payer);
    System.debug(problems);
    System.debug(problemCount);
    */

    List<Schindler_Invoice_History__c> saveList = new List<Schindler_Invoice_History__c>();
    Schindler_Invoice_History__c       newRec   = new Schindler_Invoice_History__c();
    newRec.Id                  = historyId;
    newRec.Bill_To__c	         = billTo;
    newRec.Billing_Id__c       = billingId;
    newRec.Contract__c         = contract;
    newRec.ContentVersionId__c = contentVersionId;
    newRec.Description__c      = description;
    newRec.Duns_Number__c      = dunsNumber;
    newRec.Expenses__c         = expensesDec;
    newRec.Fax__c              = fax;
    newRec.Federal_Tax_Id__c   = federalTaxId;
    newRec.Field_Contact__c    = fieldContact;
    newRec.Invoice_Date__c     = invoice_Date;
    newRec.Invoice_Number__c   = invoiceNumber;
    newRec.Invoice_Total__c    = invoiceTotalDec;
    newRec.Labor__c            = laborDec;
    newRec.Local_Office__c     = localOffice;
    newRec.Notification__c     = notification;
    newRec.Order_No__c         = orderNo;
    newRec.Order_Type__c       = orderType;
    newRec.Payer__c            = payer;
    newRec.Remit_To__c         = remitTo;
    newRec.Sales_Contact__c    = salesContact;
    newRec.Service_Location__c = serviceLocation;
    newRec.Sub_Total__c        = subTotalDec;
    newRec.Tax__c              = taxDec;
    newRec.Telephone__c        = telephone;
    newRec.Problems__c         = problems;
    newRec.Problem_Count__c    = problemCountInt;
    saveList.add(newRec);
    String retVal,errors;
    Database.SaveResult[] srList = Database.update(saveList, false);
    for (Database.SaveResult sr : srList) {
      if (sr.isSuccess()) {
        retVal = sr.getId();
      }
      else {
        for(Database.Error err : sr.getErrors()) {
          System.debug(err.getStatusCode() + ': ' + err.getMessage());
          errors += err.getMessage() + ' ';
        }
        retVal = 'Errors: ' + errors;
      }
    }
    return retVal;
  }
  
}