force-app/main/default/objects/Case/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invoice record of the Pdf associated with this case.</description>
    <label>Invoice</label>
    <referenceTo>Schindler_Invoice_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Group_Email__c</fullName>
    <formula>Invoice__r.Account__r.Group_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Group Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Customer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comments__c</fullName>
    <inlineHelpText>Any Comment the customer wishes to share about this invoice</inlineHelpText>
    <label>Customer Comments</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EmailAlertCaseDisputeService.cls
public without sharing class EmailAlertCaseDisputeService {

    @InvocableMethod(label='Dispute Case' description='Send Disputes to Vendors' category='Case')
    public static void sendInvoiceEmails(List<Id> caseIds) {

        Case[] caseRecords = new Case[]{};

        caseRecords = [SELECT
                        Invoice__c,
                        Invoice__r.Customer_Comments__c,
                        Invoice__r.Account__r.Group_Email__c,
                        Invoice__r.Account__r.Customer_Accounts_Contact__c,
                        Invoice__r.Account__r.Vendor_Accounts_Contact__c,
                        Contact.Email,
                        Invoice_Group_Email__c
                        FROM Case
                        WHERE Id IN :caseIds];

        Id[] invoiceIds = new Id[] {};
        for (Case caseRecord :caseRecords) {
            invoiceIds.add(caseRecord.Invoice__c);
        }

        ContentDocumentLink[] pdfs = [SELECT ContentDocumentId,
                                            LinkedEntityId
                                        FROM ContentDocumentLink
                                        WHERE LinkedEntityId IN :invoiceIds];

        Id[] contentDocumentIds = new Id[] {};

        for (ContentDocumentLink pdf :pdfs) {
            contentDocumentIds.add(pdf.ContentDocumentId);
        }

        ContentVersion[] versions = [SELECT ContentDocumentId
                                        FROM ContentVersion
                                        WHERE ContentDocumentId IN :contentDocumentIds];

        Map<Id, Id> versionsByContentId = new Map<Id, Id>();
        for (ContentVersion version :versions) {
            versionsByContentId.put(version.ContentDocumentId, version.Id);
        }

        Map<Id, Id[]> pdfByInvoiceId = new Map<Id, Id[]>();

        for (ContentDocumentLink pdf :pdfs) {

            if (!pdfByInvoiceId.containsKey(pdf.LinkedEntityId)) {
                pdfByInvoiceId.put(pdf.LinkedEntityId, new Id[] {});
            }

            if (versionsByContentId.containsKey(pdf.ContentDocumentId)) {
                pdfByInvoiceId.get(pdf.LinkedEntityId).add(versionsByContentId.get(pdf.ContentDocumentId));
            }
        }

        EmailAlertsServiceHandler handler = new EmailAlertsServiceHandler();
        handler.sendDisputeInvoiceEmails(caseRecords, pdfByInvoiceId);
    }
}