force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Notification master</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Billing_Id__c.field-meta.xml
<CustomField>
    <fullName>Billing_Id__c</fullName>
    <label>Billing Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <inlineHelpText>For TK, equivalent to Customer #</inlineHelpText>
    <label>Contract</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>For TK, refer to Resolution Summary.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Duns_Number__c</fullName>
    <label>Duns Number</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Federal_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id__c</fullName>
    <label>Federal Tax Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Field_Contact__c.field-meta.xml
<CustomField>
    <fullName>Field_Contact__c</fullName>
    <label>Field Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number - not used</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Labor__c.field-meta.xml
<CustomField>
    <fullName>Labor__c</fullName>
    <label>Labor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Local_Office__c.field-meta.xml
<CustomField>
    <fullName>Local_Office__c</fullName>
    <label>Local Office</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <inlineHelpText>For TK, it is SR #</inlineHelpText>
    <label>Order No</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <label>Payer</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/PdfFilename__c.field-meta.xml
<CustomField>
    <fullName>PdfFilename__c</fullName>
    <label>PdfFilename</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Problem_Count__c.field-meta.xml
<CustomField>
    <fullName>Problem_Count__c</fullName>
    <label>Problem Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Problems__c.field-meta.xml
<CustomField>
    <fullName>Problems__c</fullName>
    <label>Problems</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Remit_To__c.field-meta.xml
<CustomField>
    <fullName>Remit_To__c</fullName>
    <label>Remit To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Contact__c</fullName>
    <label>Sales Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Subtotal</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceFixerControllerTest.cls
@IsTest(SeeAllData=true)
public without sharing class InvoiceFixerControllerTest {

  /*
  @testSetup static void setup() {

    Schindler_Invoice_History__c newRec   = new Schindler_Invoice_History__c();
    newRec.Bill_To__c	         = 'HEALTH SYSTEMS ACCOUNTS PAYABLE-CONTRACTS 190 E BANNOCK ST BOISE ID 83712-6241';
    newRec.Billing_Id__c       = '5000043237';
    newRec.Contract__c         = '4100086022';
    newRec.ContentVersionId__c = 'This is a test';
    newRec.Description__c      = '01/12/2019 SERVICE CALL ON ELEVATOR 71 WAS REQUESTED BY TED. CUSTOMER REPORTED: CODE 1 ENTRAPMENT ON MAIN FLOOR WITH PASSENGERS. TECHNICIAN REPORTED: FOUND FATER AND TWO SONS STUCK. FOUND TRIPPED GOVERNER SWITCH. RESET AND CHECKED OPERATION. REFER TO NOTIFICATION 62899351';
    newRec.Duns_Number__c      = '09 480 9993';
    newRec.Expenses__c         = 68.64;
    newRec.Fax__c              = '208 577 5525';
    newRec.Federal_Tax_Id__c   = '09 480 9993';
    newRec.Field_Contact__c    = 'Charles Pogue';
    newRec.Invoice_Date__c     = '2/3/2019';
    newRec.Invoice_Number__c   = '7152874823';
    newRec.Invoice_Total__c    = 537.04;
    newRec.Labor__c            = 468.4;
    newRec.Local_Office__c     = 'Schindler Elevator Corporation 743 MCGREGOR CT STE 140 BOISE ID 83705-5225';
    newRec.Notification__c     = '62899351';
    newRec.Order_No__c         = '5154057331';
    newRec.Order_Type__c       = 'Z1TM';
    newRec.Payer__c            = 'ST LUKE\'S HEALTH SYSTEM 190 E BANNOCK ST BOISE ID 83712-6241';
    newRec.PdfFilename__c      = '12345.pdf';
    newRec.Remit_To__c         = 'Schindler Elevator Corporation';
    newRec.Sales_Contact__c    = 'Diane Rawson';
    newRec.Service_Location__c = 'ST LUKES MERIDIAN MEDICAL CENTER 1102.5336. PW1 10200201.736050.76050 EAGLE RD MERIDIAN ID 83642-6308';
    newRec.Sub_Total__c        = 537.04;
    newRec.Tax__c              = 0.0;
    newRec.Telephone__c        = '208 577 5524';
    newRec.Problems__c         = 'No problems';
    newRec.Problem_Count__c    = 0;

    insert newRec;
  }
  */

  @IsTest public static void Test1() {
    List<ContentVersion> testList = [SELECT ContentSize,FileType,Id,LastModifiedDate,Title FROM ContentVersion WHERE FileType = 'JSON' AND ContentSize > 40000 ORDER BY LastModifiedDate DESC NULLS LAST LIMIT 2];
    ContentVersion testRec = testList[0];
    String jsonTitle = testRec.Title;
    String pdfTitle  = jsonTitle.replace('.json','.pdf');
    Schindler_Invoice_History__c testData = InvoiceFixerController.getInvoiceData('cvId',testRec.Id,'');
    System.debug('testData');
    System.debug(testData);
    System.assertNotEquals(testData.ContentVersionId__c,null,'Test data is not empty');

    Schindler_Invoice_History__c testData2 = InvoiceFixerController.getInvoiceData('Pdf','',pdfTitle);
    System.debug('testData2');
    System.debug(testData2);
    System.assertNotEquals(testData2.ContentVersionId__c,null,'Test data2 is not empty');    
  }

}