force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Notification master</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Billing_Id__c.field-meta.xml
<CustomField>
    <fullName>Billing_Id__c</fullName>
    <label>Billing Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <inlineHelpText>For TK, equivalent to Customer #</inlineHelpText>
    <label>Contract</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>For TK, refer to Resolution Summary.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Duns_Number__c</fullName>
    <label>Duns Number</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Federal_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id__c</fullName>
    <label>Federal Tax Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Field_Contact__c.field-meta.xml
<CustomField>
    <fullName>Field_Contact__c</fullName>
    <label>Field Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number - not used</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Labor__c.field-meta.xml
<CustomField>
    <fullName>Labor__c</fullName>
    <label>Labor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Local_Office__c.field-meta.xml
<CustomField>
    <fullName>Local_Office__c</fullName>
    <label>Local Office</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <inlineHelpText>For TK, it is SR #</inlineHelpText>
    <label>Order No</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <label>Payer</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/PdfFilename__c.field-meta.xml
<CustomField>
    <fullName>PdfFilename__c</fullName>
    <label>PdfFilename</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Problem_Count__c.field-meta.xml
<CustomField>
    <fullName>Problem_Count__c</fullName>
    <label>Problem Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Problems__c.field-meta.xml
<CustomField>
    <fullName>Problems__c</fullName>
    <label>Problems</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Remit_To__c.field-meta.xml
<CustomField>
    <fullName>Remit_To__c</fullName>
    <label>Remit To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Contact__c</fullName>
    <label>Sales Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Subtotal</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceFixerController.cls
public without sharing class InvoiceFixerController {
  
  @AuraEnabled (cacheable=true) 
  public static Schindler_Invoice_History__c getInvoiceData(String CurrentInput,String JsonContentVersionId,String PdfFilename) {
    String filename,jsonTitle,pdfTitle,cvId;

    System.debug('CurrentInput: ' + CurrentInput );
    System.debug('JsonContentVersionId: ' + JsonContentVersionId );
    System.debug('PdfFilename: ' + PdfFilename );
    List<Schindler_Invoice_History__c> dataList;
    Schindler_Invoice_History__c data;

    if(CurrentInput == 'Pdf') {
      if(PdfFilename.toLowerCase().endsWith('.pdf')) {
        pdfTitle = PdfFilename;
      } else {
        pdfTitle = PdfFilename + '.pdf';
      }
      jsonTitle = pdfTitle.replace('.pdf','.json');
      List<ContentVersion> jsonCvList = [SELECT Id,Title,CreatedDate FROM ContentVersion WHERE Title = :jsonTitle ORDER BY LastModifiedDate DESC NULLS LAST LIMIT 2];
      ContentVersion jsonCvRec = jsonCvList[0];
      cvId = jsonCvRec.Id;
    } else {
      cvId = JsonContentVersionId;
      ContentVersion jsonCvRec = [SELECT Title FROM ContentVersion WHERE Id = :JsonContentVersionId];
      jsonTitle = jsonCvRec.Title.toLowerCase();
      pdfTitle  = jsonTitle.replace('.json','.pdf');
    }

    dataList = [SELECT PdfFilename__c,Billing_Id__c,Bill_To__c,ContentVersionId__c,Contract__c,Description__c,Duns_Number__c,Expenses__c,Fax__c,Federal_Tax_Id__c,Field_Contact__c,Id,Invoice_Date__c,Invoice_Number__c,Invoice_Total__c,Labor__c,Local_Office__c,Notification__c,Order_No__c,Order_Type__c,Payer__c,Problems__c,Problem_Count__c,Remit_To__c,Sales_Contact__c,Service_Location__c,Sub_Total__c,Tax__c,Telephone__c FROM Schindler_Invoice_History__c WHERE ContentVersionId__c = :cvId ORDER BY CreatedDate DESC NULLS LAST];    System.debug('cvId: ' + cvId );
    data = dataList[0];
    System.debug('jsonTitle: ' + jsonTitle );
    System.debug('pdfTitle: '  + pdfTitle );
    
    return data;
  }

}