force-app/main/default/objects/Request_Update__e/Request_Update__e.object-meta.xml
<CustomObject>
    <label>Request Update</label>
    <pluralLabel>Request Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Request_Update__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Salesforce Record Id of the Notification</description>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PortalNotificationController.cls
public with sharing class PortalNotificationController {


    @AuraEnabled
    public static void requestUpdates(Id[] equipmentIds) {

        if (equipmentIds != null) {

            Request_Update__e[] events = new Request_Update__e[] {};

            for (Id equipmentId :equipmentIds) {

                Request_Update__e eventRecord = new Request_Update__e(Record_Id__c = equipmentId);
                events.add(eventRecord);
            }

            EventBus.publish(events);
        }
    }

}