force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Billing_Id__c.field-meta.xml
<CustomField>
    <fullName>Billing_Id__c</fullName>
    <label>Billing Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <inlineHelpText>For TK, equivalent to Customer #</inlineHelpText>
    <label>Contract</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>For TK, refer to Resolution Summary.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Duns_Number__c</fullName>
    <label>Duns Number</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Federal_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id__c</fullName>
    <label>Federal Tax Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Field_Contact__c.field-meta.xml
<CustomField>
    <fullName>Field_Contact__c</fullName>
    <label>Field Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Labor__c.field-meta.xml
<CustomField>
    <fullName>Labor__c</fullName>
    <label>Labor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Local_Office__c.field-meta.xml
<CustomField>
    <fullName>Local_Office__c</fullName>
    <label>Local Office</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <inlineHelpText>For TK, it is SR #</inlineHelpText>
    <label>Order No</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Contact__c</fullName>
    <label>Sales Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Subtotal</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OCRStrategySchindler.cls
public with sharing class OCRStrategySchindler extends OCRStrategy {

    public OCRStrategySchindler() {
        super();
    }

    public override Schindler_Invoice_History__c createInvoice() {

        loadMaps();

        Schindler_Invoice_History__c result = new Schindler_Invoice_History__c();

        Integer index = null;
        Integer index2 = null;
        Integer boundaryIndex = 0;


        // Local Office
        index = indexByText.get('Office');
        if (index != null) {
            result.Local_Office__c = ocrByIndex.get(index + 1).getLine();
        }

        // Bill To
        index = indexByText.get('Bill');
        index2 = indexByText.get('to');

        if (index != null) {
            result.Bill_To__c = ocrByIndex.get(index + 1).getLine() + '\n';
        }

        if (index2 != null) {
            result.Bill_To__c += ocrByIndex.get(index2 + 1).getLine();
        }


        // Service Location
        index = indexByText.get('Service');
        index2 = indexByText.get('Location');

        if (index != null) {
            result.Service_Location__c = ocrByIndex.get(index + 1).getLine() + '\n';
        }

        if (index2 != null) {
            result.Service_Location__c += ocrByIndex.get(index2 + 1).getLine();
        }

        // Invoice Number
        index = indexByText.get('Invoice Number');
        if (index != null) {
            result.Name = ocrByIndex.get(index + 1).getLine();
        }

        // Invoice Date
        index = indexByText.get('Invoice Date');
        if (index != null) {
            String invoiceDate = ocrByIndex.get(index + 1).getLine();

            try {
                result.Invoice_Date__c = Date.parse(invoiceDate);
            }
            catch (TypeException ex) {
                result.Invoice_Date__c = null;
            }
        }

        // Billing Id
        index = indexByText.get('Billing ID');
        if (index != null) {
            result.Billing_Id__c = ocrByIndex.get(index + 1).getLine();
        }

        // Sales Contact
        index = indexByText.get('Sales Contact');
        if (index != null) {
            result.Sales_Contact__c = ocrByIndex.get(index + 1).getLine();
        }

        // Field Contact
        index = indexByText.get('Field Contact');
        if (index != null) {
            result.Field_Contact__c = ocrByIndex.get(index + 1).getLine();
        }

        // Telephone
        index = indexByText.get('Telephone');
        if (index != null) {
            result.Telephone__c = ocrByIndex.get(index + 1).getLine();
        }

        // Fax
        index = indexByText.get('Fax');
        if (index != null) {
            result.Fax__c = ocrByIndex.get(index + 1).getLine();
        }

        // Federal Tax ID
        index = indexByText.get('Federal Tax ID');
        if (index != null) {
            result.Federal_Tax_Id__c = ocrByIndex.get(index + 1).getLine();
        }

        // DUNS Number
        index = indexByText.get('DUNS Number');
        if (index != null) {
            result.Duns_Number__c = ocrByIndex.get(index + 1).getLine();
        }

        // Order Type
        index = indexByText.get('Order Type');
        if (index != null) {
            result.Order_Type__c = ocrByIndex.get(index + 1).getLine();
        }

        // Order Number
        index = indexByText.get('Order No');
        if (index != null) {
            result.Order_No__c = ocrByIndex.get(index + 1).getLine();
        }

        // Contract
        index = indexByText.get('Contract');
        if (index != null) {
            result.Contract__c = ocrByIndex.get(index + 1).getLine();
        }

        // Description
        index = indexByText.get('Description');
        if (index != null) {
            boundaryIndex = indexByText.get('Labor');

            if (boundaryIndex != null) {

                String[] descriptions = new String[] {};

                for (Integer i = index; i < boundaryIndex - 1; i++) {
                    descriptions.add(ocrByIndex.get(i + 1).getLine());
                }

                result.Description__c = String.join(descriptions, '\n');
            }
        }

        // Labor
        index = indexByText.get('Labor');
        if (index != null) {
            String labor = ocrByIndex.get(index + 1).getLine();

            if (labor != null) {
                labor = labor.remove('$');

                try {
                    result.Labor__c = Decimal.valueOf(labor);
                }
                catch (TypeException ex) {
                    result.Labor__c = null;
                }
            }
        }

        // Expenses
        index = indexByText.get('Expenses');
        if (index != null) {
            String expenses = ocrByIndex.get(index + 1).getLine();

            if (expenses != null) {
                expenses = expenses.remove('$');

                try {
                    result.Expenses__c = Decimal.valueOf(expenses);
                }
                catch (TypeException ex) {
                    result.Expenses__c = null;
                }
            }
        }

        // Subtotal
        index = indexByText.get('Subtotal');
        if (index != null) {
            String subTotal = ocrByIndex.get(index + 1).getLine();

            if (subTotal != null) {
                subTotal = subTotal.remove('$');

                try {
                    result.Sub_Total__c = Decimal.valueOf(subTotal);
                }
                catch (TypeException ex) {
                    result.Sub_Total__c = null;
                }
            }
        }

        // Tax
        index = indexByText.get('Tax');
        if (index != null) {
            String tax = ocrByIndex.get(index + 1).getLine();

            if (tax != null) {
                tax = tax.remove('$');
                try {
                    result.Tax__c = Decimal.valueOf(tax);
                }
                catch (TypeException ex) {
                    result.Tax__c = null;
                }
            }
        }

        // Total Invoice Amount
        index = indexByText.get('Total Invoice Amount');

        if (index != null) {
            String totalInvoiceAmount = ocrByIndex.get(index + 1).getLine();

            if (totalInvoiceAmount != null) {
                totalInvoiceAmount = totalInvoiceAmount.remove('$');
                try {
                    result.Invoice_Total__c = Decimal.valueOf(totalInvoiceAmount);
                }
                catch (TypeException ex) {
                    result.Invoice_Total__c = null;
                }
            }
        }

        return result;
    }


}