force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <inlineHelpText>For TK, equivalent to Customer #</inlineHelpText>
    <label>Contract</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Service__c</fullName>
    <description>Date the service was received.</description>
    <inlineHelpText>Date the service was received.</inlineHelpText>
    <label>Date of Service</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Days_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Pay__c</fullName>
    <inlineHelpText>Invoice Days to Pay</inlineHelpText>
    <label>Days To Pay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>For TK, refer to Resolution Summary.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <inlineHelpText>For TK, it is SR #</inlineHelpText>
    <label>Order No</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Subtotal</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OCRStrategyThyssen.cls
public with sharing class OCRStrategyThyssen extends OCRStrategy {

    public OCRStrategyThyssen() {
        super();
    }

    public override Schindler_Invoice_History__c createInvoice() {

        loadMaps();

        Schindler_Invoice_History__c result = new Schindler_Invoice_History__c();

        Integer index = null;
        Integer index2 = null;
        Integer boundaryIndex = 0;

        // Invoice Date
        index = indexByText.get('INVOICE DATE:');
        if (index != null) {
            String invoiceDate = ocrByIndex.get(index + 1).getLine();
            try {
                result.Invoice_Date__c = Date.parse(invoiceDate);
            }
            catch (TypeException ex) {
                result.Invoice_Date__c = null;
            }
        }

        // Order Number
        index = indexByText.get('SR #:');
        if (index != null) {
            result.Order_No__c = ocrByIndex.get(index + 1).getLine();
        }

        // Invoice Number
        index = indexByText.get('INVOICE #:');
        if (index != null) {
            result.Name = ocrByIndex.get(index + 1).getLine();
        }

        // Contract Number
        index = indexByText.get('CUSTOMER #:');
        if (index != null) {
            result.Contract__c = ocrByIndex.get(index + 1).getLine();
        }

        // Days to Pay
        index = indexByText.get('TERMS:');
        if (index != null) {
            result.Days_To_Pay__c = ocrByIndex.get(index + 1).getLine();
        }

        // Total Due
        index = indexByText.get('TOTAL DUE:');
        if (index != null) {

            String totalInvoiceAmount = ocrByIndex.get(index + 1).getLine();

            if (totalInvoiceAmount != null) {
                totalInvoiceAmount = totalInvoiceAmount.remove('$');
                try {
                    result.Invoice_Total__c = Decimal.valueOf(totalInvoiceAmount);
                }
                catch (TypeException ex) {
                    result.Invoice_Total__c = null;
                }
            }
        }

        // Bill To
        index = indexByText.get('BILL TO:');
        if (index != null) {

            Set<String> billAddresses = new Set<String>();

            for (Integer i = index; i < index + 8; i++) {

                String line = ocrByIndex.get(index + 1).getLine();

                if (line.containsIgnoreCase('Reported By')) {
                    break;
                }
                else if (line.containsIgnoreCase('SHIP TO')) {
                    // Ignore Ship Title
                    continue;
                }
                else {
                    line = line.trim();
                    billAddresses.add(line);
                }
            }

            result.Bill_To__c = String.join(new List<String>(billAddresses), '\n');
        }

        // Service Date - Tricky One
        index = indexByText.get('AMOUNT');
        if (index != null) {
            // We need to iterate to find the Date = 10 lines max distance
            for (Integer i = index; i < index + 10; i++) {

                String potentialDate = ocrByIndex.get(i + 1).getLine();
                potentialDate = potentialDate.trim();

                // Evaluate date format
                if ((potentialDate.length() == 10) && (potentialDate.indexOf('/') == 2) && (potentialDate.lastIndexOf('/') == 5)) {
                    try {
                        result.Date_of_Service__c = Date.parse(potentialDate);
                        break;
                    }
                    catch (TypeException ex) {
                        result.Date_of_Service__c = null;
                    }
                }
            }
        }

        // Description
        result.Description__c = getDescription();

        // Subtotal
        index = indexByText.get('PLEASE PAY THIS AMOUNT');
        if (index != null) {
            String subTotal = ocrByIndex.get(index + 1).getLine();

            if (subTotal != null) {
                subTotal = subTotal.remove('$');
                try {
                    result.Sub_Total__c = Decimal.valueOf(subTotal);
                }
                catch (TypeException ex) {
                    result.Sub_Total__c = null;
                }
            }
        }

        // Tax
        index = indexByText.get('PLEASE PAY THIS AMOUNT');
        if (index != null) {
            String tax = ocrByIndex.get(index + 2).getLine();

            if (tax != null) {
                tax = tax.remove('$');
                try {
                    result.Tax__c = Decimal.valueOf(tax);
                }
                catch (TypeException ex) {
                    result.Tax__c = null;
                }
            }
        }

        return result;
    }

    private String getDescription() {

        Integer index = null;

        // Find Resolution Summary
        for (String key :indexByText.keySet()) {

            if (key.containsIgnoreCase('Resolution Summary')) {
                index = indexByText.get(key);
                break;
            }
        }

        if (index == null) {
            return '';
        }

        // We expect no more than 10 lines of Description
        String[] descriptions = new String[] {};
        for (Integer i = index; index < index + 10; i++) {

            String text = ocrByIndex.get(i).getLine();

            if (text.equals('DATE')) {
                break;
            }

            descriptions.add(text);
        }

        return String.join(descriptions, '\n');
    }
}