force-app/main/default/objects/Account/fields/Auditmate_Email__c.field-meta.xml
<CustomField>
    <fullName>Auditmate_Email__c</fullName>
    <inlineHelpText>Google email associated to the account - for receiving notifications, etc</inlineHelpText>
    <label>Auditmate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Accounts Payable Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Customer Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Group_Email__c</fullName>
    <description>Email used to send notifications on behalf of the customer</description>
    <label>Group Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailAlertInvoiceForwardService.cls
public without sharing class EmailAlertInvoiceForwardService {


    @InvocableMethod(label='Forward Invoice' description='Forward Invoice to Customer' category='Invoice')
    public static void sendInvoiceEmails(List<Id> accountIds) {

        Map<String, Id> templatesByName = new Map<String,Id>();

        EmailTemplate[] templates = [SELECT DeveloperName
                                        FROM EmailTemplate
                                        WHERE IsActive = true];

        for (EmailTemplate template :templates) {
            templatesByName.put(template.DeveloperName, template.Id);
        }

        Id templateId = templatesByName.get('fwd_invoice_request');


        Messaging.SingleEmailMessage[] emails = new Messaging.SingleEmailMessage[] {};

        for (Account accountRecord :[SELECT
                                        Auditmate_Email__c,
                                        Group_Email__c,
                                        Vendor_Contact__r.Email
                                        FROM Account WHERE Id IN :accountIds])
        {


            emails.add(createEmail(accountRecord, templateId));

        }

        if (!Test.isRunningTest()) {
            Messaging.sendEmail(emails);
        }
    }


    private static Messaging.SingleEmailMessage createEmail(Account accountRecord, Id templateId) {

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email = Messaging.renderStoredEmailTemplate(templateId, null, accountRecord.Id);
        email.setOrgWideEmailAddressId(accountRecord.Group_Email__c);
        email.setToAddresses(new String[] { accountRecord.Vendor_Contact__r.Email });
        email.setCcAddresses(new String[] { accountRecord.Customer_Accounts_Contact__r.Email });

        return email;
    }

}