force-app/main/default/objects/Account/fields/Customer_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Accounts Payable Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Customer Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Group_Email__c</fullName>
    <description>Email used to send notifications on behalf of the customer</description>
    <label>Group Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Accounts Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <formula>Vendor_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>IF(Invoice__r.Customer_Contact_Name__c != null, Invoice__r.Customer_Contact_Name__c, Equipment__r.Customer_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>Opportunity__r.Vendor_Contract_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Opportunity__r.Account.Customer_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>Opportunity__r.Vendor_Contract_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Maintenance_Date__c</fullName>
    <formula>IF( UPPER(TEXT(Opportunity__r.Frequency_of_service__c)) == &apos;PERIODICALLY&apos;,
NULL,
Last_Maintenance_Date__c + 30
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Equipment_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Vendor&apos;s unique ID for this equipment.</inlineHelpText>
    <label>Vendor Equipment #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <formula>Opportunity__r.Account.Vendor_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Account.Customer_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <description>Elevator company&apos;s customer number</description>
    <label>Elevator Vendor&apos;s Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contract_Number__c</fullName>
    <inlineHelpText>Vendor&apos;s contract Number, also known as Customer Number.  Schindler data seems to label the same field two ways.</inlineHelpText>
    <label>Vendor Contract Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Email__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Email__c</fullName>
    <formula>Account.Vendor_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailAlertEquipmentService.cls
public without sharing class EmailAlertEquipmentService {

    @InvocableMethod(label='Send Requests' description='Send Requests to Vendors' category='Equipment')
    // public static void sendServiceEmails(List<Id> equipmentIds) {

    //     Equipment__c[] equipments = new Equipment__c[]{};

    //     equipments = [SELECT
    //                     Opportunity__r.Account.Group_Email__c,
    //                     Opportunity__r.Account.Customer_Accounts_Contact__c,
    //                     Opportunity__r.Account.Vendor_Accounts_Contact__c,
    //                     Opportunity__r.Account.Customer_Accounts_Contact__r.Email,
    //                     Opportunity__r.Account.Vendor_Accounts_Contact__r.Email,
    //                     Opportunity__r.Account.Vendor_Contact__r.Email,
    //                     Opportunity__r.Vendor_Email__c
    //                 FROM Equipment__c
    //                 WHERE Id IN :equipmentIds];

    //     EmailAlertsServiceHandler handler = new EmailAlertsServiceHandler();
    //     handler.sendServiceEmails(equipments);
    // }

    public static void sendServiceEmails(List<Id> caseIds) {

        Case[] cases = new Case[] {};

        cases = [SELECT
                        Equipment__c,
                        Equipment__r.Vendor_Name__c,
                        Equipment__r.Customer_Number__c,
                        Equipment__r.Next_Maintenance_Date__c,
                        Equipment__r.Vendor_Equipment_No__c,
                        Equipment__r.Customer_Name__c,

                        Opportunity__r.Vendor_Contract_Number__c,
                        Opportunity__r.Account.Group_Email__c,
                        Opportunity__r.Account.Customer_Accounts_Contact__c,
                        Opportunity__r.Account.Vendor_Accounts_Contact__c,
                        Opportunity__r.Account.Customer_Accounts_Contact__r.Email,
                        Opportunity__r.Account.Vendor_Accounts_Contact__r.Email,
                        Opportunity__r.Account.Vendor_Contact__r.Email,
                        Opportunity__r.Vendor_Email__c
                    FROM Case
                    WHERE Id IN :caseIds];

        EmailAlertsServiceHandler handler = new EmailAlertsServiceHandler();
        handler.sendServiceEmails(cases);
    }
}