force-app/main/default/objects/Account/fields/Customer_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Accounts Payable Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Customer Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Customer Contact</description>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Elevator_Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Elevator_Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Group_Email__c</fullName>
    <description>Email used to send notifications on behalf of the customer</description>
    <label>Group Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Accounts Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Schindler_Invoice_History__c.field-meta.xml
<CustomField>
    <fullName>Schindler_Invoice_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Schindler_Invoice_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Equipment_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Vendor&apos;s unique ID for this equipment.</inlineHelpText>
    <label>Vendor Equipment #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Elevator_Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Elevator_Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency_of_service__c.field-meta.xml
<CustomField>
    <fullName>Frequency_of_service__c</fullName>
    <label>Frequency of service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Bi-Annually</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Periodically</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start date of contract between Elevator vendor and their client</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Estimate_Number__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Number__c</fullName>
    <label>Estimate Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor rep that send the proposal</description>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Mate_Support_Status__c.field-meta.xml
<CustomField>
    <fullName>Mate_Support_Status__c</fullName>
    <inlineHelpText>Invoice will be visible to customer when &quot;Verified as Invalid&quot; or &quot;Verified as Valid&quot; are selected</inlineHelpText>
    <label>Mate Support Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Verified as Invalid</fullName>
            </value>
            <value>
                <fullName>Verified as Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity is populated by class SchindlerOcrProcess if it can find a match on Contract Number.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor invoice was received from.</description>
    <inlineHelpText>Vendor invoice was received from.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice History (Vendor)</relationshipLabel>
    <relationshipName>Invoice_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Vendor Activities</relationshipLabel>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/EquipNo__c.field-meta.xml
<CustomField>
    <fullName>EquipNo__c</fullName>
    <label>EquipNo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Inspection__c/State_Inspection__c.object-meta.xml
<CustomObject>
    <label>State Inspection</label>
    <nameField>
        <label>State Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Inspection__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>State Inspections</relationshipLabel>
    <relationshipName>State_Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Inspection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>State Inspections</relationshipLabel>
    <relationshipName>State_Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PortalTests.cls
@isTest
private with sharing class PortalTests {

    private static Account accountRecord = null;
    private static Account elevatorRecord = null;
    private static Schindler_Invoice_History__c invoiceRecord = null;
    private static Schindler_Maintenance_Activity__c activityRecord = null;
    private static Proposal__c proposalRecord = null;
    private static Opportunity opportunityRecord = null;
    private static Equipment__c equipmentRecord = null;
    private static Case caseRecord = null;
    private static User userRecord = null;

    @isTest
    private static void coverEquipmentNotificationUpdateBatch() {

        setup();

        Test.startTest();
        Database.executeBatch(new EquipmentNotificationUpdateBatch());
        Test.stopTest();

        System.assert(true, 'true');
    }

    @isTest
    private static void coverPortalActivityController() {

        setup();

        Test.startTest();

        PortalActivityController.getMaintenanceActivityCount(accountRecord.Id);
        PortalActivityController.getTestingFiveActivityCount(accountRecord.Id);
        PortalActivityController.getTestingOneActivityCount(accountRecord.Id);

        Test.stopTest();

        System.assert(true, 'true');

    }


    @isTest
    private static void coverPortalNotificationController() {

        setup();

        Test.startTest();

        PortalNotificationController.requestUpdates(new Id[] {equipmentRecord.Id});

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverEmailAlertServices() {

        setup();

        Test.startTest();

        EmailAlertProposalDeclineService.sendDeclineEmails(new Id[] {proposalRecord.Id});
        EmailAlertInvoicePayService.sendInvoiceEmails(new Id[] {invoiceRecord.Id});
        EmailAlertInvoiceDisputeService.sendInvoiceEmails(new Id[] {invoiceRecord.Id});
        EmailAlertEquipmentService.sendServiceEmails(new Id[] {caseRecord.Id});

        EmailAlertCaseDisputeService.sendInvoiceEmails(new Id[] {caseRecord.Id});
        EmailAlertInvoiceForwardService.sendInvoiceEmails(new Id[] {accountRecord.Id});

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverPortalController() {

        setup();

        Test.startTest();

        Id accountId = accountRecord.Id;

        PortalController.getServicePreventiveActivities(accountId);
        PortalController.getServiceTestingActivities(accountId);
        PortalController.getServiceRepairActivities(accountId);
        PortalController.getServiceCallbackActivities(accountId);

        PortalController.getServiceAllActivities(accountId, 'TODAY');
        PortalController.getServicePeriodActivities(accountId, Date.today(), Date.today());

        PortalController.getFinanceOpenInvoices(accountId);
        PortalController.getFinanceDisputedInvoices(accountId);
        PortalController.getFinanceAllInvoices(accountId);

        PortalController.getUpcomingActivities(accountId);
        PortalController.getPreventiveActivities(accountId);
        PortalController.getTestingActivities(accountId);
        PortalController.getRepairActivities(accountId);
        PortalController.getCallbacksActivities(accountId);

        PortalController.getTodayActivities(accountId);
        PortalController.getThisWeekActivities(accountId);
        PortalController.getLastWeekActivities(accountId);
        PortalController.getThisMonthActivities(accountId);
        PortalController.getLastMonthActivities(accountId);
        PortalController.getAllActivities(accountId, 'TODAY');

        PortalController.getActivities(accountId, Date.today(), Date.today());
        PortalController.getUnits(UserInfo.getUserId(), accountId);
        PortalController.getUnitsAndInspections(UserInfo.getUserId(), accountId);
        PortalController.getInvoices(UserInfo.getUserId(), accountId);
        PortalController.getOpenInvoices(UserInfo.getUserId(), accountId);
        PortalController.getDisputedInvoices(UserInfo.getUserId(), accountId);
        PortalController.getPaidInvoices(UserInfo.getUserId(), accountId);
        PortalController.getDueInvoices(UserInfo.getUserId(), accountId);

        PortalController.getInspectionFindings(accountId);
        PortalController.getStateRecords(accountId);
        PortalController.getStateRecordInspections(accountId);
        PortalController.getStateRecordsWithInspections(UserInfo.getUserId(), accountId);

        PortalController.getOpenProposals(accountId);
        PortalController.getAcceptedProposals(UserInfo.getUserId(), accountId);
        PortalController.getProposalsHistory(accountId);

        PortalControllerHelper.getUnits(accountId);

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverPortalFileController() {

        setup();

        Test.startTest();

        Id accountId = accountRecord.Id;
        PortalFileController.getContentDocumentId(accountId);

        Test.stopTest();

        System.assert(true, 'true');
    }

    @isTest
    private static void coverWrappers() {

        PortalEquipmentWrapper wrapper = new PortalEquipmentWrapper(null, null);
        System.assert(true, 'true');
    }

    @isTest
    private static void coverPortalFinanceController() {

        setup();

        Test.startTest();

        Id invoiceId = invoiceRecord.Id;

        PortalFinanceController.addCustomerComment(invoiceId, 'message');
        PortalFinanceController.addVendorComment(invoiceId, 'message');

        PortalFinanceController.disputeInvoice(invoiceId, 'message');
        // PortalFinanceController.payInvoice(invoiceId);
        PortalFinanceController.acceptInvoice(invoiceId);
        PortalFinanceController.renegociateInvoice(invoiceId, 'message');

        invoiceRecord.Mate_Support_Status__c = 'Verified as Invalid';
        PortalFinanceController.getTemplateText(invoiceRecord);

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverPortalContractController() {

        setup();

        Test.startTest();

        Id accountId = accountRecord.Id;

        PortalContractController.getActiveContract(accountId);

        Test.stopTest();

        System.assert(true, 'true');
    }

    @isTest
    private static void coverPortalProposalController() {

        setup();

        Test.startTest();

        Id proposalId = proposalRecord.Id;

        PortalProposalController.acceptProposal(proposalId, '');
        PortalProposalController.declineProposal(proposalId, '');

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverGetEquipmentWrappers() {

        Equipment__c equipment = new Equipment__c(Vendor_Equipment_No__c = '1234');
        Schindler_Maintenance_Activity__c activity = new Schindler_Maintenance_Activity__c(EquipNo__c = '1234');

        Test.startTest();

        PortalControllerHelper.getEquipmentWrappers(new Equipment__c[] {equipment}, new Schindler_Maintenance_Activity__c[] {activity});

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverPortalInsightsController() {

        setup();

        Test.startTest();

        PortalInsightsController.getInsights(accountRecord.Id);

        Test.stopTest();

        System.assert(true, 'true');

    }

    @isTest
    private static void coverPortalCaseController() {

        setup();
        setupUser();

        Test.startTest();

        System.runAs(userRecord) {
            PortalCaseController.createContractCase(null);
            PortalCaseController.createInspectionCase(null);
            PortalCaseController.createProposalCase(null);
        }

        Test.stopTest();

        System.assert(true, 'true');
    }

    @isTest
    private static void coverCustomerUserHandler() {

        setup();
        setupUser();

        Test.startTest();

        Id accountId = accountRecord.Id;

        Id ownerId = UserInfo.getUserId();

        System.runAs(userRecord) {

            CustomerUserHandler.getDefaultAccountId();
            CustomerUserHandler.createNewContact('lastName', 'phone', 'email@dnsaj.com', null, ownerId);
            CustomerUserHandler.updateExistingAccount(accountRecord.Id, null, null);
            CustomerUserHandler.getAccounts();
            CustomerUserHandler.getDirectPartnerAccountId();
            CustomerUserHandler.getCommunityContact();
            CustomerUserHandler.setDefaultAccountId(accountId);
            CustomerUserHandler.setAccountVendor(elevatorRecord.Id, 'username', 'password');

        }

        Test.stopTest();

        System.assert(true, 'true');
    }

    @isTest
    private static void testPortalLoginController() {

        Test.startTest();

        PortalLoginController.login('username', 'password');

        Test.stopTest();

        System.assert(true, 'true');

    }

    private static void setup() {

        // OWA are visible in tests
        OrgWideEmailAddress address = [SELECT Id
                                        FROM OrgWideEmailAddress
                                        LIMIT 1];


        Contact ap = new Contact(LastName = 'Last Name');
        ap.Email = 'test@test.com';
        insert ap;

        ContentVersion versionRecord = new ContentVersion();
        versionRecord.FirstPublishLocationId = ap.Id;
        versionRecord.PathOnClient = 'file.txt';
        versionRecord.VersionData = Blob.valueOf('Test');
        versionRecord.Title = 'Test Document';
        insert versionRecord;

        versionRecord = [SELECT ContentDocumentId
                            FROM ContentVersion
                            WHERE Id = :versionRecord.Id];

        elevatorRecord = new Account(Name = 'Test Elevator');
        insert elevatorRecord;

        accountRecord = new Account(Name = 'Test Account');
        accountRecord.Customer_Accounts_Contact__c = ap.Id;
        accountRecord.Vendor_Accounts_Contact__c = ap.Id;
        accountRecord.Customer_Contact__c = ap.Id;
        accountRecord.Vendor_Contact__c = ap.Id;
        accountRecord.Elevator_Vendor_Account__c = elevatorRecord.Id;
        accountRecord.Group_Email__c = address.Id;
        insert accountRecord;

        opportunityRecord = new Opportunity(Name = 'Test Opportunity', AccountId = accountRecord.Id);
        opportunityRecord.CloseDate = Date.today();
        opportunityRecord.Start_Date__c = Date.today().addYears(-1);
        opportunityRecord.StageName = 'In Review';
        opportunityRecord.RecordTypeId = '0123k0000014QkLAAU';
        opportunityRecord.Frequency_of_service__c = 'Monthly';
        insert opportunityRecord;

        proposalRecord = new Proposal__c(Name = 'Test Proposal');
        proposalRecord.Vendor__c = 'Test Vendor';
        proposalRecord.Estimate_Number__c = 'Test Proposal';
        proposalRecord.Opportunity__c = opportunityRecord.Id;
        proposalRecord.CustomerStatus__c = 'Accepted';
        insert proposalRecord;

        insert new ContentDocumentLink(ContentDocumentId = versionRecord.ContentDocumentId, LinkedEntityId = proposalRecord.Id);

        equipmentRecord = new Equipment__c(Name = 'Test Equipment');
        equipmentRecord.Opportunity__c = opportunityRecord.Id;
        equipmentRecord.Next_PM_Date__c = Date.today().addDays(-1);
        equipmentRecord.Display_Name__c = 'Test';
        insert equipmentRecord;

        State_Inspection__c inspectionRecord = new State_Inspection__c(Name = 'Test Inspection');
        inspectionRecord.Opportunity__c = opportunityRecord.Id;
        inspectionRecord.Type_of_Inspection__c = 'ANNUAL';
        insert inspectionRecord;

        activityRecord = new Schindler_Maintenance_Activity__c(Opportunity__c = opportunityRecord.Id);
        activityRecord.VisitDate__c = Date.today().addDays(-1);
        activityRecord.Type__c = PortalConstants.TESTING_TYPE;
        activityRecord.Category__c = PortalConstants.CATEGORY_1;
        activityRecord.Equipment__c = equipmentRecord.Id;
        activityRecord.Description__c = 'CAT1';
        insert activityRecord;

        activityRecord = new Schindler_Maintenance_Activity__c(Opportunity__c = opportunityRecord.Id);
        activityRecord.VisitDate__c = Date.today().addDays(-1);
        activityRecord.Type__c = PortalConstants.TESTING_TYPE;
        activityRecord.Category__c = PortalConstants.CATEGORY_5;
        activityRecord.Equipment__c = equipmentRecord.Id;
        activityRecord.Description__c = 'CAT5';
        insert activityRecord;

        activityRecord = new Schindler_Maintenance_Activity__c(Opportunity__c = opportunityRecord.Id);
        activityRecord.VisitDate__c = Date.today().addDays(-1);
        activityRecord.Type__c = PortalConstants.CALLBACK_TYPE;
        activityRecord.Equipment__c = equipmentRecord.Id;
        activityRecord.Description__c = 'CAT1';
        insert activityRecord;

        activityRecord = new Schindler_Maintenance_Activity__c(Opportunity__c = opportunityRecord.Id);
        activityRecord.VisitDate__c = Date.today().addDays(-1);
        activityRecord.Type__c = PortalConstants.MAINTENANCE_TYPE;
        activityRecord.Equipment__c = equipmentRecord.Id;
        activityRecord.Description__c = 'CAT1';
        insert activityRecord;

        activityRecord = new Schindler_Maintenance_Activity__c(Opportunity__c = opportunityRecord.Id);
        activityRecord.VisitDate__c = Date.today().addDays(-1);
        activityRecord.Type__c = PortalConstants.MAINTENANCE_TYPE;
        activityRecord.Departure_DateTime__c = Datetime.now();
        activityRecord.Equipment__c = equipmentRecord.Id;
        activityRecord.Description__c = 'CAT1';
        insert activityRecord;

        insert new ContentDocumentLink(ContentDocumentId = versionRecord.ContentDocumentId, LinkedEntityId = activityRecord.Id);

        invoiceRecord = new Schindler_Invoice_History__c(Name = 'Test Invoice');
        invoiceRecord.Opportunity__c = opportunityRecord.Id;
        invoiceRecord.UserStatus__c = PortalConstants.DISPUTE_STATUS;
        invoiceRecord.Account__c = accountRecord.Id;
        invoiceRecord.Mate_Support_Status__c = PortalController.VAV;
        invoiceRecord.Customer_Email__c = 'test@test.com';
        insert invoiceRecord;

        invoiceRecord = new Schindler_Invoice_History__c(Name = 'Test Invoice');
        invoiceRecord.Opportunity__c = opportunityRecord.Id;
        invoiceRecord.UserStatus__c = PortalConstants.PAY_STATUS;
        invoiceRecord.Mate_Support_Status__c = PortalController.VAV;
        invoiceRecord.Account__c = accountRecord.Id;
        invoiceRecord.Customer_Email__c = 'test@test.com';
        insert invoiceRecord;

        invoiceRecord = new Schindler_Invoice_History__c(Name = 'Test Invoice');
        invoiceRecord.Opportunity__c = opportunityRecord.Id;
        invoiceRecord.Account__c = accountRecord.Id;
        invoiceRecord.Mate_Support_Status__c = PortalController.VAV;
        invoiceRecord.Customer_Email__c = 'test@test.com';
        insert invoiceRecord;

        caseRecord = new Case();
        caseRecord.ContactId = ap.Id;
        caseRecord.Invoice__c = invoiceRecord.Id;
        caseRecord.Priority = 'High';
        caseRecord.Reason = 'Invoice Dispute';
        caseRecord.Type = 'Invoice Review';
        caseRecord.Origin = 'Web';
        caseRecord.Status = 'New';

        insert caseRecord;

        insert new ContentDocumentLink(ContentDocumentId = versionRecord.ContentDocumentId, LinkedEntityId = invoiceRecord.Id);

    }

    private static void setupUser() {

        Id profileId = [SELECT Id
                            FROM Profile
                            WHERE Id = '00e3k00000104JO'].Id;


        Contact contactRecord = new Contact(LastName = 'Test Contact', AccountId = accountRecord.Id);
        insert contactRecord;

        userRecord = new User(Alias = 'User1234',
                                Email = 'test123@noemail.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'Testing',
                                LanguageLocaleKey = 'en_US',
                                LocalesIdKey = 'en_US',
                                ProfileId = profileId,
                                Country = 'United States',
                                IsActive = true,
                                ContactId = contactRecord.Id,
                                TimezonesIdKey = 'America/Los_Angeles',
                                Username = 'tester@noemail.com');

        insert userRecord;
    }


}