force-app/main/default/objects/Account/fields/Customer_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Accounts Payable Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Customer Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Group_Email__c</fullName>
    <description>Email used to send notifications on behalf of the customer</description>
    <label>Group Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Accounts_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Accounts_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Accounts Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Accounts Contact)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Vendor Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailAlertInvoicePayService.cls
public without sharing class EmailAlertInvoicePayService {

    @InvocableMethod(label='Pay Invoice' description='Send Invoices to Customer' category='Invoice')
    public static void sendInvoiceEmails(List<Id> invoiceIds) {

        Schindler_Invoice_History__c[] invoices = new Schindler_Invoice_History__c[]{};

        invoices = [SELECT
                        Account__r.Group_Email__c,
                        Account__r.Customer_Accounts_Contact__c,
                        Account__r.Vendor_Accounts_Contact__c,
                        Account__r.Customer_Accounts_Contact__r.Email,
                        Account__r.Vendor_Accounts_Contact__r.Email,
                        Account__r.Vendor_Contact__r.Email
                        FROM Schindler_Invoice_History__c
                        WHERE Id IN :invoiceIds];

        ContentDocumentLink[] pdfs = [SELECT ContentDocumentId,
                                            LinkedEntityId
                                        FROM ContentDocumentLink
                                        WHERE LinkedEntityId IN :invoiceIds];

        Id[] contentDocumentIds = new Id[] {};

        for (ContentDocumentLink pdf :pdfs) {
            contentDocumentIds.add(pdf.ContentDocumentId);
        }

        ContentVersion[] versions = [SELECT ContentDocumentId
                                        FROM ContentVersion
                                        WHERE ContentDocumentId IN :contentDocumentIds];

        Map<Id, Id> versionsByContentId = new Map<Id, Id>();
        for (ContentVersion version :versions) {
            versionsByContentId.put(version.ContentDocumentId, version.Id);
        }

        Map<Id, Id[]> pdfByInvoiceId = new Map<Id, Id[]>();

        for (ContentDocumentLink pdf :pdfs) {

            if (!pdfByInvoiceId.containsKey(pdf.LinkedEntityId)) {
                pdfByInvoiceId.put(pdf.LinkedEntityId, new Id[] {});
            }

            if (versionsByContentId.containsKey(pdf.ContentDocumentId)) {
                pdfByInvoiceId.get(pdf.LinkedEntityId).add(versionsByContentId.get(pdf.ContentDocumentId));
            }
        }

        EmailAlertsServiceHandler handler = new EmailAlertsServiceHandler();
        handler.sendPaidInvoiceEmails(invoices, pdfByInvoiceId);
    }

}