force-app/main/default/objects/Account/fields/Elevator_Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Elevator_Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Group_Email__c</fullName>
    <description>Email used to send notifications on behalf of the customer</description>
    <label>Group Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Company__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Company__c</fullName>
    <label>Vendor Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vendor_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Schindler_Invoice_History__c.field-meta.xml
<CustomField>
    <fullName>Schindler_Invoice_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Schindler_Invoice_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Elevator_Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Elevator_Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Contract_Stage__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contract_Stage__c</fullName>
    <label>Vendor Contract Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Verification</fullName>
            </value>
            <value>
                <fullName>Data Loading</fullName>
            </value>
            <value>
                <fullName>Vendor_Contract_Active</fullName>
                <label>Vendor Contract Active</label>
            </value>
            <value>
                <fullName>Vendor Contract - Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor invoice was received from.</description>
    <inlineHelpText>Vendor invoice was received from.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice History (Vendor)</relationshipLabel>
    <relationshipName>Invoice_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <displayFormat>VEN-{0000}</displayFormat>
        <label>Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Vendor_Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Thyssen</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler</fullName>
    </customValue>
    <customValue>
        <fullName>Kone</fullName>
    </customValue>
    <customValue>
        <fullName>Otis</fullName>
    </customValue>
    <masterLabel>Vendor Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OCRTests.cls
@isTest
public with sharing class OCRTests {

    @isTest
    private static void testSchindlerInvoiceError() {

        Case[] records = [SELECT Id FROM Case WHERE Subject = 'Schindler Invoice Received'];

        Test.setMock(HttpCalloutMock.class, new OCRTestMock.OCRSchindlerTestMock(500));

        Test.startTest();

        if (!records.isEmpty()) {

            OCRCaseButtonController controller = new OCRCaseButtonController(new ApexPages.StandardController(records[0]));
            controller.createInvoiceAction();
        }

        Test.stopTest();

        Schindler_Invoice_History__c[] invoices = [SELECT Id FROM Schindler_Invoice_History__c];
        System.assert(!invoices.isEmpty(), 'Invoices cannot be empty');
    }

    @isTest
    private static void testThyssenInvoiceError() {

        Case[] records = [SELECT Id FROM Case WHERE Subject = 'Thyssen Invoice Received'];

        Test.setMock(HttpCalloutMock.class, new OCRTestMock.OCRThyssenTestMock(500));

        Test.startTest();

        if (!records.isEmpty()) {

            OCRCaseButtonController controller = new OCRCaseButtonController(new ApexPages.StandardController(records[0]));
            controller.createInvoiceAction();
        }

        Test.stopTest();

        Schindler_Invoice_History__c[] invoices = [SELECT Id FROM Schindler_Invoice_History__c];
        System.assert(!invoices.isEmpty(), 'Invoices cannot be empty');
    }

    @isTest
    private static void testSchindlerKone() {

        OCRStrategyKone strategy = new OCRStrategyKone();
        strategy.createInvoice();

        System.assert(true, 'Invoices cannot be empty');
    }

    @isTest
    private static void testSchindlerInvoice() {

        Case[] records = [SELECT Id FROM Case WHERE Subject = 'Schindler Invoice Received'];

        Test.setMock(HttpCalloutMock.class, new OCRTestMock.OCRSchindlerTestMock());

        Test.startTest();

        if (!records.isEmpty()) {

            OCRCaseButtonController controller = new OCRCaseButtonController(new ApexPages.StandardController(records[0]));
            controller.createInvoiceAction();
        }

        Test.stopTest();

        Schindler_Invoice_History__c[] invoices = [SELECT Id FROM Schindler_Invoice_History__c];
        System.assert(!invoices.isEmpty(), 'Invoices cannot be empty');
    }

    @isTest
    private static void testThyssenInvoice() {

        Case[] records = [SELECT Id FROM Case WHERE Subject = 'Thyssen Invoice Received'];

        Test.setMock(HttpCalloutMock.class, new OCRTestMock.OCRThyssenTestMock());

        Test.startTest();

        if (!records.isEmpty()) {

            OCRCaseButtonController controller = new OCRCaseButtonController(new ApexPages.StandardController(records[0]));
            controller.createInvoiceAction();
        }

        Test.stopTest();

        Schindler_Invoice_History__c[] invoices = [SELECT Id FROM Schindler_Invoice_History__c];
        System.assert(!invoices.isEmpty(), 'Invoices cannot be empty');
    }

    @TestSetup
    private static void setup() {

        // OWA are visible in tests
        OrgWideEmailAddress address = [SELECT Id
                                        FROM OrgWideEmailAddress
                                        LIMIT 1];


        Contact ap = new Contact(LastName = 'Last Name');
        ap.Email = 'test@test.com';
        insert ap;

        ContentVersion versionRecord = new ContentVersion();
        versionRecord.FirstPublishLocationId = ap.Id;
        versionRecord.PathOnClient = 'file.txt';
        versionRecord.VersionData = Blob.valueOf('Test');
        versionRecord.Title = 'Test Document';
        insert versionRecord;

        versionRecord = [SELECT ContentDocumentId
                            FROM ContentVersion
                            WHERE Id = :versionRecord.Id];

        Account schindlerRecord = new Account(Name = 'Schindler');
        schindlerRecord.Vendor_Company__c = 'Schindler';
        insert schindlerRecord;

        Account thyssenRecord = new Account(Name = 'Thyssen');
        thyssenRecord.Vendor_Company__c = 'Thyssen';
        insert thyssenRecord;

        Account schindlerCustomerRecord = new Account(Name = 'Schindler Customer');
        schindlerCustomerRecord.Group_Email__c = address.Id;
        schindlerCustomerRecord.Elevator_Vendor_Account__c = schindlerRecord.Id;
        insert schindlerCustomerRecord;

        Account thyssenCustomerRecord = new Account(Name = 'Thyssen Customer');
        thyssenCustomerRecord.Group_Email__c = address.Id;
        thyssenCustomerRecord.Elevator_Vendor_Account__c = thyssenRecord.Id;
        insert thyssenCustomerRecord;

        Opportunity schindlerContract = new Opportunity(Name = 'Schindler Contract');
        schindlerContract.AccountId = schindlerCustomerRecord.Id;
        schindlerContract.Elevator_Vendor_Account__c = schindlerRecord.Id;
        schindlerContract.CloseDate = Date.today();
        schindlerContract.StageName = 'Closed Won';
        schindlerContract.Vendor_Contract_Stage__c = 'Vendor_Contract_Active';
        insert schindlerContract;

        Opportunity thyssenContract = new Opportunity(Name = 'Thyssen Contract');
        thyssenContract.AccountId = schindlerCustomerRecord.Id;
        thyssenContract.Elevator_Vendor_Account__c = schindlerRecord.Id;
        thyssenContract.CloseDate = Date.today();
        thyssenContract.StageName = 'Closed Won';
        thyssenContract.Vendor_Contract_Stage__c = 'Vendor_Contract_Active';
        insert thyssenContract;

        Case schindlerCase = new Case(Subject = 'Schindler Invoice Received');
        schindlerCase.Type = 'Invoice Review';
        schindlerCase.Reason = 'New Invoice';
        schindlerCase.Origin = 'Web';
        schindlerCase.Status = 'New';
        schindlerCase.AccountId = schindlerCustomerRecord.Id;
        schindlerCase.Vendor__c = schindlerRecord.Id;
        insert schindlerCase;

        Case thyssenCase = new Case(Subject = 'Thyssen Invoice Received');
        thyssenCase.Type = 'Invoice Review';
        thyssenCase.Reason = 'New Invoice';
        thyssenCase.Origin = 'Web';
        thyssenCase.Status = 'New';
        thyssenCase.AccountId = thyssenCustomerRecord.Id;
        thyssenCase.Vendor__c = thyssenRecord.Id;
        insert thyssenCase;

        insert new ContentDocumentLink(ContentDocumentId = versionRecord.ContentDocumentId, LinkedEntityId = thyssenCase.Id);
        insert new ContentDocumentLink(ContentDocumentId = versionRecord.ContentDocumentId, LinkedEntityId = schindlerCase.Id);
    }

}