force-app/main/default/objects/Account/fields/Elevator_Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Elevator_Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Elevator_Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Elevator_Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contract_Number__c</fullName>
    <inlineHelpText>Vendor&apos;s contract Number, also known as Customer Number.  Schindler data seems to label the same field two ways.</inlineHelpText>
    <label>Vendor Contract Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <inlineHelpText>Date Customer Approves Invoice</inlineHelpText>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Audit_Comments__c.field-meta.xml
<CustomField>
    <fullName>Audit_Comments__c</fullName>
    <inlineHelpText>Mates comments about this invoice, visible to the customer.</inlineHelpText>
    <label>Audit Comments</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Customer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comments__c</fullName>
    <inlineHelpText>Any Comment the customer wishes to share about this invoice</inlineHelpText>
    <label>Customer Comments</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Disputed_Date__c.field-meta.xml
<CustomField>
    <fullName>Disputed_Date__c</fullName>
    <description>Date dispute was clicked by customer.</description>
    <label>Disputed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Mate_Support_Status__c.field-meta.xml
<CustomField>
    <fullName>Mate_Support_Status__c</fullName>
    <inlineHelpText>Invoice will be visible to customer when &quot;Verified as Invalid&quot; or &quot;Verified as Valid&quot; are selected</inlineHelpText>
    <label>Mate Support Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Verified as Invalid</fullName>
            </value>
            <value>
                <fullName>Verified as Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity is populated by class SchindlerOcrProcess if it can find a match on Contract Number.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/UserStatus__c.field-meta.xml
<CustomField>
    <fullName>UserStatus__c</fullName>
    <inlineHelpText>External Status that is visible to Portal User</inlineHelpText>
    <label>User Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Awaiting User Action</fullName>
            </value>
            <value>
                <fullName>Renegotiate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor invoice was received from.</description>
    <inlineHelpText>Vendor invoice was received from.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice History (Vendor)</relationshipLabel>
    <relationshipName>Invoice_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PortalFinanceController.cls
public without sharing class PortalFinanceController {

    private static final String INVALID_INVOICE = 'Verified as Invalid';

    @AuraEnabled
    public static void payInvoice(Id invoiceId) {

        Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c(Id = invoiceId);
        invoice.UserStatus__c = PortalConstants.PAY_STATUS;
        invoice.Approved_Date__c = Date.today();
        update invoice;
    }

    @AuraEnabled
    public static void acceptInvoice(Id invoiceId) {

        Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c(Id = invoiceId);
        invoice.UserStatus__c = PortalConstants.AWAITING_STATUS;
        update invoice;
    }

    @AuraEnabled
    public static void disputeInvoice(Id invoiceId, String message) {

        Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c(Id = invoiceId);
        invoice.UserStatus__c = PortalConstants.DISPUTE_STATUS;
        invoice.Disputed_Date__c = Date.today();
        invoice.Customer_Comments__c = message;
        update invoice;
    }

    @AuraEnabled
    public static void renegociateInvoice(Id invoiceId, String message) {

        Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c(Id = invoiceId);
        invoice.UserStatus__c = PortalConstants.RENEGOCIATE_STATUS;
        invoice.Customer_Comments__c = message;
        update invoice;
    }

    @AuraEnabled
    public static void addCustomerComment(Id invoiceId, String message) {

        Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c(Id = invoiceId);
        invoice.Customer_Comments__c = message;
        update invoice;
    }

    @AuraEnabled
    public static void addVendorComment(Id invoiceId, String message) {

        Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c(Id = invoiceId);
        invoice.Customer_Comments__c = message;
        update invoice;
    }

    @AuraEnabled
    public static String getTemplateText(Schindler_Invoice_History__c record) {

        String result = null;

        if (INVALID_INVOICE.equalsIgnoreCase(record.Mate_Support_Status__c)) {

            result = 'Hi ' + record.Opportunity__r.Elevator_Vendor_Account__r.Name + ',\n\n' +
            'Customer #: ' + record.Opportunity__r.Vendor_Contract_Number__c + '\n' +
            'Invoice #: ' + record.Name  + '\n\n' +
            'The attached invoice is being disputed for the following reason: \n\n' +
            + record.Audit_Comments__c + '\n\n' +
            'Please credit or revise the invoice in accordance with the contract terms and reply back with confirmation.\n\n' +
            'Thank you,\n\n' +
            record.Account__r.Name + '\n\n';
        }

        return result;
    }

}

// invoiceId: this.record.Id, status: this.record.Mate_Support_Status__c, vendorName: this.record.Vendor__r.Name, customerName: this.record.Account__r.Name