force-app/main/default/objects/Account/fields/Group_Email__c.field-meta.xml
<CustomField>
    <fullName>Group_Email__c</fullName>
    <description>Email used to send notifications on behalf of the customer</description>
    <label>Group Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Maintenance_Date__c</fullName>
    <formula>IF( UPPER(TEXT(Opportunity__r.Frequency_of_service__c)) == &apos;PERIODICALLY&apos;,
NULL,
Last_Maintenance_Date__c + 30
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_PM_Date__c</fullName>
    <label>Next PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Past_Due__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Past Due</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Email__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Email__c</fullName>
    <formula>Account.Vendor_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EquipmentNotificationUpdateBatch.cls
public with sharing class EquipmentNotificationUpdateBatch implements Database.Batchable<sObject>, Schedulable {

    public void execute(SchedulableContext sc) {

        Database.executeBatch(new EquipmentNotificationUpdateBatch());
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {

        Date today = Date.today();

        return Database.getQueryLocator('SELECT Past_Due__c, Opportunity__r.Account.Group_Email__c, Opportunity__r.Vendor_Email__c FROM Equipment__c WHERE Next_Maintenance_Date__c < :today OR Next_PM_Date__c < :today');
    }

    public void execute(Database.BatchableContext bc, Equipment__c[] scope) {

        for (Equipment__c record :scope) {
            record.Past_Due__c = true;
        }

        update scope;
    }

    public void finish(Database.BatchableContext bc) {
        // Nothing to execute
    }

}