force-app/main/default/objects/Account/fields/Vendor_Company__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Company__c</fullName>
    <label>Vendor Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vendor_Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Schindler_Invoice_History__c.field-meta.xml
<CustomField>
    <fullName>Schindler_Invoice_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Schindler_Invoice_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Contract_Stage__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contract_Stage__c</fullName>
    <label>Vendor Contract Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Verification</fullName>
            </value>
            <value>
                <fullName>Data Loading</fullName>
            </value>
            <value>
                <fullName>Vendor_Contract_Active</fullName>
                <label>Vendor Contract Active</label>
            </value>
            <value>
                <fullName>Vendor Contract - Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Case that has the Pdf of invoice</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>For TK, refer to Resolution Summary.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Mate_Support_Status__c.field-meta.xml
<CustomField>
    <fullName>Mate_Support_Status__c</fullName>
    <inlineHelpText>Invoice will be visible to customer when &quot;Verified as Invalid&quot; or &quot;Verified as Valid&quot; are selected</inlineHelpText>
    <label>Mate Support Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Verified as Invalid</fullName>
            </value>
            <value>
                <fullName>Verified as Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity is populated by class SchindlerOcrProcess if it can find a match on Contract Number.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/UserStatus__c.field-meta.xml
<CustomField>
    <fullName>UserStatus__c</fullName>
    <inlineHelpText>External Status that is visible to Portal User</inlineHelpText>
    <label>User Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Awaiting User Action</fullName>
            </value>
            <value>
                <fullName>Renegotiate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor invoice was received from.</description>
    <inlineHelpText>Vendor invoice was received from.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice History (Vendor)</relationshipLabel>
    <relationshipName>Invoice_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <displayFormat>VEN-{0000}</displayFormat>
        <label>Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Vendor_Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Thyssen</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler</fullName>
    </customValue>
    <customValue>
        <fullName>Kone</fullName>
    </customValue>
    <customValue>
        <fullName>Otis</fullName>
    </customValue>
    <masterLabel>Vendor Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OCRServiceUtils.cls
public with sharing class OCRServiceUtils {

    // Auxiliary methods

    public static Case getCase(Id caseId) {

        Case[] result = [SELECT
                            AccountId,
                            Account.ParentId,
                            ContactId,
                            Vendor__c,
                            Vendor__r.Vendor_Company__c
                        FROM Case
                        WHERE Id = :caseId];

        return result.isEmpty() ? null : result[0];
    }

    public static Id getOpportunityId(Case record) {

        Opportunity[] result = [SELECT Id
                                FROM Opportunity
                                WHERE Vendor_Contract_Stage__c = 'Vendor_Contract_Active'
                                AND IsWon = true
                                AND AccountId = :record.AccountId];

        return result.isEmpty() ? null : result[0].Id;

    }

    public static ContentVersion getCaseContentVersion(Id recordId) {

        ContentVersion[] result = new ContentVersion[] {};

        ContentDocumentLink[] links = [SELECT
                                            ContentDocumentId,
                                            ContentDocument.LatestPublishedVersionId
                                        FROM ContentDocumentLink
                                        WHERE LinkedEntityId = :recordId];

        if (!links.isEmpty()) {

            Id contentVersionId = links[0].ContentDocument.LatestPublishedVersionId;

            result = [SELECT
                            ContentDocumentId,
                            VersionData
                        FROM ContentVersion
                        WHERE Id = :contentVersionId];
        }

        return result.isEmpty() ? null : result[0];
    }

    public static Schindler_Invoice_History__c insertInvoice(Object page, Case caseRecord, ContentVersion contentVersionRecord) {

        Type classType = getStrategy(caseRecord);

        if (classType == null) {
            String unverifiedMessage = 'The invoice was not correcly verified.'
                                     + ' Please review the attached file';
            return insertDummyInvoice(caseRecord, contentVersionRecord, unverifiedMessage);
        }

        OCRStrategy strategy = (OCRStrategy) classType.newInstance();
        strategy.setStream(page);

        Schindler_Invoice_History__c invoice = strategy.createInvoice();

        if (invoice != null) {

            // Information from Case
            invoice.Case__c = caseRecord.Id;
            invoice.Vendor__c = caseRecord.Vendor__c;
            invoice.Account__c = caseRecord.AccountId;
            invoice.Opportunity__c = getOpportunityId(caseRecord);

            // Audit Information
            invoice.UserStatus__c = null;
            invoice.Mate_Support_Status__c = 'Unverified';

            insert invoice;

            if (contentVersionRecord != null) {

                ContentDocumentLink[] links = createNewLinks(invoice, caseRecord, contentVersionRecord);

                insert links;
            }
        }

        return invoice;
    }

    public static Schindler_Invoice_History__c insertDummyInvoice(Case caseRecord, ContentVersion contentVersionRecord, String responseBody) {

            Schindler_Invoice_History__c invoice = new Schindler_Invoice_History__c();

            // Information from Case
            invoice.Case__c = caseRecord.Id;
            invoice.Vendor__c = caseRecord.Vendor__c;
            invoice.Account__c = caseRecord.AccountId;
            invoice.Opportunity__c = getOpportunityId(caseRecord);

            // Audit Information
            invoice.UserStatus__c = null;
            invoice.Mate_Support_Status__c = 'Unverified';
            invoice.Description__c = responseBody;

            insert invoice;

            if (contentVersionRecord != null) {

                ContentDocumentLink[] links = createNewLinks(invoice, caseRecord, contentVersionRecord);

                insert links;
            }

            return invoice;

    }

    private static ContentDocumentLink[] createNewLinks(Schindler_Invoice_History__c invoice, Case caseRecord, ContentVersion contentVersionRecord) {

        ContentDocumentLink[] links = new ContentDocumentLink[] {};

        ContentDocumentLink link = new ContentDocumentLink();
        link.LinkedEntityId = invoice.Id;
        link.ContentDocumentId = contentVersionRecord.ContentDocumentId;
        link.Visibility = 'AllUsers';
        link.ShareType = 'V';
        links.add(link);

        link = new ContentDocumentLink();
        link.LinkedEntityId = invoice.Account__c;
        link.ContentDocumentId = contentVersionRecord.ContentDocumentId;
        link.Visibility = 'AllUsers';
        link.ShareType = 'V';
        links.add(link);

        if (caseRecord.Account.ParentId != null) {

            link = new ContentDocumentLink();
            link.LinkedEntityId = caseRecord.Account.ParentId;
            link.ContentDocumentId = contentVersionRecord.ContentDocumentId;
            link.Visibility = 'AllUsers';
            link.ShareType = 'V';
            links.add(link);
        }

        return links;
    }

    public static Type getStrategy(Case caseRecord) {

        String vendorCompany = caseRecord.Vendor__r.Vendor_Company__c;

        Type result = null;

        switch on vendorCompany {

            when 'Thyssen' {
                result = Type.forName('OCRStrategyThyssen');
            }
            when 'Schindler' {
                result = Type.forName('OCRStrategySchindler');
            }
            when 'Kone' {
                result = Type.forName('OCRStrategyKone');
            }
            when else {
                // Nothing
            }
        }

        return result;
    }
}