force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Days_CAT1_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_CAT1_Past_Due__c</fullName>
    <label>Days CAT1 Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_CAT5_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_CAT5_Past_Due__c</fullName>
    <label>Days CAT5 Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_PM_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_PM_Past_Due__c</fullName>
    <label>Days PM Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <inlineHelpText>For Elev 01, Elev 02, - Elev 09 - Be sure to enter the 0 in front, so that it displays on CARE in chronological order.</inlineHelpText>
    <label>Display Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Has_Monthly_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Has_Monthly_Requirement__c</fullName>
    <formula>IF(ISPICKVAL(Opportunity__r.Frequency_of_service__c, &apos;Monthly&apos;),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Monthly Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_12_Month_CB_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_12_Month_CB_Count__c</fullName>
    <inlineHelpText>Number of Callbacks within the last 12 months</inlineHelpText>
    <label>Last 12 Month CB Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_12_Month_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_12_Month_Count__c</fullName>
    <label>Last 12 Month Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_12_Month_PM_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_12_Month_PM_Count__c</fullName>
    <label>Last 12 Month PM Count</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_12_Month_PM_Percent__c.field-meta.xml
<CustomField>
    <fullName>Last_12_Month_PM_Percent__c</fullName>
    <label>Last 12 Month PM Percent</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_30_Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_30_Day_Count__c</fullName>
    <label>Last 30 Day Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Cat1_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Cat1_Date__c</fullName>
    <label>Last Cat1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Cat5_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Cat5_Date__c</fullName>
    <label>Last Cat5 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_CB_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_CB_Date__c</fullName>
    <inlineHelpText>Last Callback date</inlineHelpText>
    <label>Last CB Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_PM_Date__c</fullName>
    <inlineHelpText>Last date where type = MNT</inlineHelpText>
    <label>Last PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_State_CAT5_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_State_CAT5_Date__c</fullName>
    <label>Last State CAT5 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Date__c</fullName>
    <label>Last Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Certificate_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Certificate_Expiration_Date__c</fullName>
    <label>State Certificate Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Certificate_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Certificate_Issue_Date__c</fullName>
    <label>State Certificate Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_ID__c.field-meta.xml
<CustomField>
    <fullName>State_ID__c</fullName>
    <description>Municipality equipment id number.</description>
    <inlineHelpText>Municipality equipment id number. Could also be: License #, State ID, or Certificate.</inlineHelpText>
    <label>Conveyance ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Status__c.field-meta.xml
<CustomField>
    <fullName>State_Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hydraulic</fullName>
            </value>
            <value>
                <fullName>Traction</fullName>
            </value>
            <value>
                <fullName>Geared</fullName>
            </value>
            <value>
                <fullName>Gearless</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Dumbwaiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Equipment_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Vendor&apos;s unique ID for this equipment.</inlineHelpText>
    <label>Vendor Equipment #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Visit_Count__c</fullName>
    <label>Record Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Notification master</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <formula>If(
   Or (
    User_Disabled__c = true,
    Send_Count__c = Max_Count__c
   ),
   false, 
   true
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Date_First_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_First_Sent__c</fullName>
    <label>Date First Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Date_Last_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Sent__c</fullName>
    <label>Date Last Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Max_Count__c.field-meta.xml
<CustomField>
    <fullName>Max_Count__c</fullName>
    <label>Max Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <label>NotificationType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Notification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Send_Count__c.field-meta.xml
<CustomField>
    <fullName>Send_Count__c</fullName>
    <label>Send Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/User_Disabled__c.field-meta.xml
<CustomField>
    <fullName>User_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationItem__c/NotificationItem__c.object-meta.xml
<CustomObject>
    <label>NotificationItem</label>
    <nameField>
        <label>NotificationItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NotificationItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationItem__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>NotificationItems</relationshipLabel>
    <relationshipName>NotificationItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationItem__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>NotificationItems</relationshipLabel>
    <relationshipName>NotificationItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Notification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Eq_Past_Due</fullName>
        <label>Eq Past Due</label>
    </customValue>
    <customValue>
        <fullName>Eq_Request</fullName>
        <label>Eq Request</label>
    </customValue>
    <masterLabel>Notification</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Notifications.cls
public without sharing class Notifications {

  @AuraEnabled
  public static Id[] getUpdates(Id accountId, String type) {
    List<id> idList = new List<Id>();
    List<Notification__c> notificationList = [
      SELECT Account__c,Account__r.Name,Date_First_Sent__c,Date_Last_Sent__c,Id,Max_Count__c,Send_Count__c,NotificationType__c ,User_Disabled__c,
      (SELECT Equipment__c,Equipment__r.Vendor_Equipment_No__c FROM NotificationItems__r)
      FROM Notification__c 
      WHERE Current__c = true AND NotificationType__c = :type AND Account__c = :accountId
      ORDER BY Account__r.Name, NotificationType__c, Date_Last_Sent__c Desc
    ];        
    if(notificationList.size() > 0) {
      for(Notification__c nfRec : notificationList) {
        for(NotificationItem__c itemRec : nfRec.NotificationItems__r) {
          idList.add(itemRec.Equipment__c);
        }
      }
    }
    return idList;
  }

  @AuraEnabled
  public static string requestUpdate(Id accountId, Id[] equipmentIds) {
    Map<String, NotificationItem__c> itemMap = new Map<String, NotificationItem__c>();
    List<NotificationItem__c> notificationItemInsertList = new List<NotificationItem__c>();
    Notification__c nfRec;
    Boolean noErrors=true;
    String equipNo,itemKey,itemEqNo,retVal='ok';
    Id notificationId;

    List<Notification__c> notificationUpdateList = new List<Notification__c>();
    List<Notification__c> notificationList = [
      SELECT Account__c,Account__r.Name,Date_First_Sent__c,Date_Last_Sent__c,Id,Max_Count__c,Send_Count__c,NotificationType__c ,User_Disabled__c,
      (SELECT Equipment__c,Equipment__r.Vendor_Equipment_No__c FROM NotificationItems__r)
      FROM Notification__c 
      WHERE Current__c = true AND NotificationType__c = 'Eq_Request' AND Account__c = :accountId
      ORDER BY Account__r.Name, NotificationType__c, Date_Last_Sent__c Desc
    ];    
    if(notificationList.size() > 0) {
      nfRec = notificationList[0];  // There is only 1 current NotificationType__c at any given time.
      for(NotificationItem__c itemRec : nfRec.NotificationItems__r) {
        itemEqNo = itemRec.Equipment__r.Vendor_Equipment_No__c;
        itemKey  = accountId + '-' + itemEqNo;
        itemMap.put(itemKey,itemRec);
      }
      System.debug('Do have a current notification for ' + accountId + ' [Eq_Request]');
      notificationId = nfRec.Id;
    } else {
      System.debug('Do NOT have a current notification for ' + accountId + ' [Eq_Request]');
      Notification__c newNotificationM = new Notification__c();
      newNotificationM.Account__c          = accountId;
      newNotificationM.NotificationType__c = 'Eq_Request';
      newNotificationM.Max_Count__c        = 1;
      newNotificationM.Send_Count__c       = 0;
      try {
        insert newNotificationM;
        notificationId = newNotificationM.Id;
      } catch (DmlException e) {
        retVal = 'Notification error';
        noErrors = false;
        System.debug(e);
      } 
    }

    if(noErrors) {
      List<Equipment__c> eqList = [
        SELECT Id,Opportunity__r.AccountId,Opportunity__r.Account.Name,Days_CAT1_Past_Due__c,Days_CAT5_Past_Due__c,Days_PM_Past_Due__c,Display_Name__c,Has_Monthly_Requirement__c,Last_12_Month_CB_Count__c,Last_12_Month_Count__c,Last_12_Month_PM_Count__c,Last_12_Month_PM_Percent__c,Last_30_Day_Count__c,Last_Cat1_Date__c,Last_Cat5_Date__c,Last_CB_Date__c,Last_PM_Date__c,Last_State_CAT5_Date__c,Last_Visit_Date__c,Opportunity__c,State_Certificate_Expiration_Date__c,State_Certificate_Issue_Date__c,State_ID__c,State_Status__c,Type__c ,Vendor_Equipment_No__c,Visit_Count__c 
        FROM Equipment__c 
        WHERE Id IN :equipmentIds
        ORDER BY Vendor_Equipment_No__c
      ]; 

      for(Equipment__c eqRec : eqList) {
        equipNo = eqRec.Vendor_Equipment_No__c;
        itemKey = accountId + '-' + equipNo;
        if(itemMap.containsKey(itemKey)) {
          System.debug(itemKey + ' Found in ItemMap');
        } else {
          System.debug(itemKey + ' NOT found in ItemMap');
          NotificationItem__c newItem = new NotificationItem__c();
          newItem.Equipment__c    = eqRec.Id;
          newItem.Notification__c = notificationId;
          notificationItemInsertList.add(newItem);
        }      
      }

      if(notificationItemInsertList.size() > 0) {
        try {
          insert notificationItemInsertList;
        } catch (DmlException e) {
          retVal = 'NotificationItem error';
          System.debug(e);
        }
      }
    }

    return retVal;
  }

  public static string equipmentNotifications() {
    // Populates Notification__c and NotificationItem__c for any Accounts with Equipment with 
    // Days_CAT1_Past_Due__c > 0 OR Days_CAT5_Past_Due__c > 0 OR Days_PM_Past_Due__c > 0

    Map<String, Notification__c> notificationMap = new Map<String, Notification__c>();
    Map<String, NotificationItem__c> itemMap = new Map<String, NotificationItem__c>();
    List<NotificationItem__c> notificationItemInsertList = new List<NotificationItem__c>();
    Set<Notification__c> notificationUpdateSet = new Set<Notification__c>();

    Integer sendCount,daysSince,daysSinceMod,weekCount;
    Integer daysCat1Late,daysCat5Late,daysPmLate;
    Date startDate;
    Date today = Date.today();
    Decimal weekCountD,sendCountD,daysCat1LateD,daysCat5LateD,daysPmLateD;
    String eqAccountId,eqAccountName,equipNo,displayName;
    String key,key1,key2,itemKey,accountId,name,type,itemEqNo;
    Notification__c childRec;
    Id notificationId;
    
    Boolean found;
    Notification__c nfRec;

    List<Notification__c> notificationList = [
      SELECT Account__c,Account__r.Name,Date_First_Sent__c,Date_Last_Sent__c,Id,Max_Count__c,Send_Count__c,NotificationType__c ,User_Disabled__c,
      (SELECT Equipment__c,Equipment__r.Vendor_Equipment_No__c FROM NotificationItems__r)
      FROM Notification__c 
      WHERE Current__c = true
      ORDER BY Account__r.Name, NotificationType__c, Date_Last_Sent__c Desc
    ];

    for(Notification__c nfRec1 : notificationList) {
      accountId = nfRec1.Account__c;
      type      = nfRec1.NotificationType__c;
      key =  accountId + '-' + type;
      System.debug('Key: ' + key);
      notificationMap.put(key,nfRec1);
      for(NotificationItem__c itemRec : nfRec1.NotificationItems__r) {
        itemEqNo = itemRec.Equipment__r.Vendor_Equipment_No__c;
        itemKey  = accountId + '-' + itemEqNo;
        itemMap.put(itemKey,itemRec);
      }
    }

    List<Equipment__c> eqList = [
      SELECT Id,Opportunity__r.AccountId,Opportunity__r.Account.Name,Days_CAT1_Past_Due__c,Days_CAT5_Past_Due__c,Days_PM_Past_Due__c,Display_Name__c,Has_Monthly_Requirement__c,Last_12_Month_CB_Count__c,Last_12_Month_Count__c,Last_12_Month_PM_Count__c,Last_12_Month_PM_Percent__c,Last_30_Day_Count__c,Last_Cat1_Date__c,Last_Cat5_Date__c,Last_CB_Date__c,Last_PM_Date__c,Last_State_CAT5_Date__c,Last_Visit_Date__c,Opportunity__c,State_Certificate_Expiration_Date__c,State_Certificate_Issue_Date__c,State_ID__c,State_Status__c,Type__c ,Vendor_Equipment_No__c,Visit_Count__c 
      FROM Equipment__c 
      WHERE Days_CAT1_Past_Due__c > 0 OR Days_CAT5_Past_Due__c > 0 OR Days_PM_Past_Due__c > 0
      ORDER BY Opportunity__r.AccountId,Vendor_Equipment_No__c
    ]; 

    Integer eqListLen = eqList.size();
    Integer i = 0;
    Equipment__c eqRec;
    while (i < eqListLen) {
      eqRec = eqList[i];
      equipNo        = eqRec.Vendor_Equipment_No__c;
      eqAccountId    = eqRec.Opportunity__r.AccountId;
      eqAccountName  = eqRec.Opportunity__r.Account.Name;
      found = false;
      key1   = eqAccountId + '-Eq_Past_Due';
      if(notificationMap.containsKey(key1)) {
        found = true;
        System.debug('Do have a current notification for ' + eqAccountName + ' [Eq_Past_Due]');
        nfRec = notificationMap.get(key1);
        notificationId = nfRec.Id;
      } else {
        System.debug('Do NOT have a current notification for ' + eqAccountName + ' [Eq_Past_Due]');
        Notification__c newNotificationM = new Notification__c();
        newNotificationM.Account__c          = eqAccountId;
        newNotificationM.NotificationType__c = 'Eq_Past_Due';
        newNotificationM.Max_Count__c        = 3;
        newNotificationM.Send_Count__c       = 0;
        newNotificationM.Date_First_Sent__c  = null;
        newNotificationM.Date_Last_Sent__c   = null;
        newNotificationM.User_Disabled__c    = false;
        try {
          insert newNotificationM;
          notificationId = newNotificationM.Id;
        } catch (DmlException e) {
          System.debug(e);
        }        
      }
      while (i < eqListLen && eqAccountId == eqList[i].Opportunity__r.AccountId) {
        eqRec   = eqList[i];
        equipNo = eqRec.Vendor_Equipment_No__c;
        itemKey = eqAccountId + '-' + equipNo;
        if(itemMap.containsKey(itemKey)) {
          System.debug(itemKey + ' Found in ItemMap');
        } else {
          System.debug(itemKey + ' NOT found in ItemMap');
          NotificationItem__c newItem = new NotificationItem__c();
          newItem.Equipment__c    = eqRec.Id;
          newItem.Notification__c = notificationId;
          notificationItemInsertList.add(newItem);
          if(found) {
            nfRec.Date_First_Sent__c = today; // Reset first send and send count.
            nfRec.Send_Count__c      = 0;
            notificationUpdateSet.add(nfRec);
          }
        }
        i++;
      }
    }
    System.debug('notificationItemInsertList:');
    System.debug(notificationItemInsertList);
    System.debug('notificationUpdateSet:');
    System.debug(notificationUpdateSet);
    try {
      insert notificationItemInsertList;
    } catch (DmlException e) {
      System.debug(e);
    }
    if(notificationUpdateSet.size() > 0) {
      List<Notification__c> notificationUpdateList = new List<Notification__c>(notificationUpdateSet);
      try {
        update notificationUpdateList;
      }
        catch (DmlException e) {
        System.debug(e);
      }
    }
    return 'ok';
  }

}