force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hydraulic</fullName>
            </value>
            <value>
                <fullName>Traction</fullName>
            </value>
            <value>
                <fullName>Geared</fullName>
            </value>
            <value>
                <fullName>Gearless</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Dumbwaiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency_of_service__c.field-meta.xml
<CustomField>
    <fullName>Frequency_of_service__c</fullName>
    <label>Frequency of service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Bi-Annually</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Periodically</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Months_Since_Start__c.field-meta.xml
<CustomField>
    <fullName>Months_Since_Start__c</fullName>
    <formula>MONTH( TODAY() ) + (( 12 * (YEAR(TODAY())- YEAR(Start_Date__c))) - MONTH(Start_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Months Since Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start date of contract between Elevator vendor and their client</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Vendor_Contract.recordType-meta.xml
<RecordType>
    <fullName>Vendor_Contract</fullName>
    <active>true</active>
    <businessProcess>Vendor Contract</businessProcess>
    <description>Vendor Contract</description>
    <label>Vendor Contract</label>
</RecordType>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Vendor Activities</relationshipLabel>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/VisitDate__c.field-meta.xml
<CustomField>
    <fullName>VisitDate__c</fullName>
    <label>VisitDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PortalActivityController.cls
public without sharing class PortalActivityController {

    @AuraEnabled
    public static ActivityWrapper getMaintenanceActivityCount(Id accountId) {

        ActivityWrapper wrapper = new ActivityWrapper();

        Opportunity[] opportunities = [SELECT
                                            Start_Date__c,
                                            Months_Since_Start__c,
                                            Frequency_of_service__c,

                                            (SELECT Id FROM Equipments__r)

                                        FROM Opportunity
                                        WHERE AccountId = :accountId
                                        AND Frequency_of_service__c = 'Monthly'
                                        AND RecordType.DeveloperName = 'Vendor_Contract'];

        if (!opportunities.isEmpty()) {

            Opportunity opportunityRecord = opportunities[0];
            Decimal valueSinceStart = Math.ceil(opportunityRecord.Months_Since_Start__c);

            wrapper = execute(opportunityRecord.Id, valueSinceStart, 'MNT', 0, 0);
            wrapper.setFrequency(true);
        }

        return wrapper;
    }

    @AuraEnabled
    public static ActivityWrapper getTestingOneActivityCount(Id accountId) {

        ActivityWrapper wrapper = new ActivityWrapper();

        Opportunity[] opportunities = [SELECT
                                            Start_Date__c,
                                            Months_Since_Start__c,
                                            Frequency_of_service__c,

                                            (SELECT Id FROM Equipments__r)

                                        FROM Opportunity
                                        WHERE AccountId = :accountId
                                        AND RecordType.DeveloperName = 'Vendor_Contract'];

        if (!opportunities.isEmpty()) {

            Opportunity opportunityRecord = opportunities[0];
            Decimal valueSinceStart = opportunityRecord.Months_Since_Start__c / 12;
            valueSinceStart = Math.ceil(valueSinceStart);

            wrapper = execute(opportunityRecord.Id, valueSinceStart, 'TEST', 1, opportunityRecord.Equipments__r.size());
        }

        wrapper.setFrequency(true);
        return wrapper;

    }

    @AuraEnabled
    public static ActivityWrapper getTestingFiveActivityCount(Id accountId) {

        ActivityWrapper wrapper = new ActivityWrapper();

        Opportunity[] opportunities = [SELECT
                                            Start_Date__c,
                                            Months_Since_Start__c,
                                            Frequency_of_service__c,

                                            (SELECT Id FROM Equipments__r)

                                        FROM Opportunity
                                        WHERE AccountId = :accountId
                                        AND RecordType.DeveloperName = 'Vendor_Contract'];

        if (!opportunities.isEmpty()) {

            Opportunity opportunityRecord = opportunities[0];

            Decimal valueSinceStart = opportunityRecord.Months_Since_Start__c / (12 * 5);
            valueSinceStart = Math.ceil(valueSinceStart);

            wrapper = execute(opportunityRecord.Id, valueSinceStart, 'TEST', 5, opportunityRecord.Equipments__r.size());
        }

        wrapper.setFrequency(true);
        return wrapper;
    }


    private static ActivityWrapper execute(Id opportunityId, Decimal valueSinceStart, String activityType, Integer testLength, Integer equipmentCount) {

        ActivityWrapper wrapper = new ActivityWrapper(testLength, equipmentCount);

        Equipment__c[] equipmentsWithActivities = new Equipment__c[] {};

        equipmentsWithActivities = [SELECT Name,
                                        (SELECT
                                            VisitDate__c,
                                            Description__c
                                        FROM Schindler_Maintenance_Activities__r
                                        WHERE Type__c = :activityType
                                        AND Opportunity__c = :opportunityId)
                                    FROM Equipment__c
                                    WHERE Opportunity__c = :opportunityId];

        for (Equipment__c equipmentWithActivities :equipmentsWithActivities) {

            Map<Date, Integer> activitiesByDate = new Map<Date, Integer>();

            Integer activityCount = equipmentWithActivities.Schindler_Maintenance_Activities__r.size();

            Decimal incompleteActivities = valueSinceStart - activityCount;

            wrapper.incompletedActivities += incompleteActivities.intValue();

            Schindler_Maintenance_Activity__c[] activityRecords = getRelevantActivities(equipmentWithActivities.Schindler_Maintenance_Activities__r, testLength);

            for (Schindler_Maintenance_Activity__c activityRecord :activityRecords) {

                Date initialVisitDate = null;

                if (testLength == 0) {
                    initialVisitDate = activityRecord.VisitDate__c.toStartOfMonth();
                }
                else {
                    initialVisitDate = Date.newInstance(activityRecord.VisitDate__c.year(), 1, 1);
                }


                if (!activitiesByDate.containsKey(initialVisitDate)) {
                    activitiesByDate.put(initialVisitDate, 0);
                }

                Integer value = activitiesByDate.get(initialVisitDate);
                activitiesByDate.put(initialVisitDate, ++value);

            }

            for (Integer value :activitiesByDate.values()) {

                wrapper.completedActivities ++;
                wrapper.lateActivities += value - 1;
            }

            wrapper.sanitizeValues();
        }

        return wrapper;

    }

    private static Schindler_Maintenance_Activity__c[] getRelevantActivities(Schindler_Maintenance_Activity__c[] records, Integer testLength) {

        Schindler_Maintenance_Activity__c[] result = new Schindler_Maintenance_Activity__c[] {};

        if (testLength == 0) {
            result = records;
        }
        else {

            for (Schindler_Maintenance_Activity__c record :records) {

                String description = record.Description__c;

                if (testLength == 5 && description.containsIgnoreCase('CAT5')) {
                    result.add(record);
                }
                else if (testLength == 1 && (description.containsIgnoreCase('CAT1') || description.containsIgnoreCase('ANNUAL'))) {
                    result.add(record);
                }
            }
        }

        return result;
    }

    public class ActivityWrapper {

        @AuraEnabled
        public Integer completedActivities {get; set;}

        @AuraEnabled
        public Integer incompletedActivities {get; set;}

        @AuraEnabled
        public Integer lateActivities {get; set;}

        @AuraEnabled
        public Boolean isMonthlyFrequency {get; set;}

        public Integer testLength;
        public Integer recordCount;

        public ActivityWrapper() {

            lateActivities = 0;
            incompletedActivities = 0;
            completedActivities = 0;
            isMonthlyFrequency = null;
        }

        public ActivityWrapper(Integer testLength, Integer recordCount) {

            this();

            this.testLength = testLength;
            this.recordCount = recordCount;
        }

        public void setFrequency(Boolean value) {
            isMonthlyFrequency = value;
        }

        public void sanitizeValues() {

            if (incompletedActivities < 0) {
                incompletedActivities = 0;
            }

            if (testLength == 5) {

                Integer totalTasks = completedActivities + incompletedActivities + lateActivities;

                if (totalTasks < recordCount) {
                    incompletedActivities += recordCount - totalTasks;
                }
            }

        }
    }

}