force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Days_CAT1_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_CAT1_Past_Due__c</fullName>
    <label>Days CAT1 Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_CAT5_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_CAT5_Past_Due__c</fullName>
    <label>Days CAT5 Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_PM_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_PM_Past_Due__c</fullName>
    <label>Days PM Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Date__c</fullName>
    <label>Last Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Equipment_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Vendor&apos;s unique ID for this equipment.</inlineHelpText>
    <label>Vendor Equipment #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Notification master</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Date_First_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_First_Sent__c</fullName>
    <label>Date First Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Date_Last_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Sent__c</fullName>
    <label>Date Last Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Max_Count__c.field-meta.xml
<CustomField>
    <fullName>Max_Count__c</fullName>
    <label>Max Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <label>NotificationType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Notification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Send_Count__c.field-meta.xml
<CustomField>
    <fullName>Send_Count__c</fullName>
    <label>Send Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/User_Disabled__c.field-meta.xml
<CustomField>
    <fullName>User_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationItem__c/NotificationItem__c.object-meta.xml
<CustomObject>
    <label>NotificationItem</label>
    <nameField>
        <label>NotificationItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NotificationItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationItem__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>NotificationItems</relationshipLabel>
    <relationshipName>NotificationItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationItem__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>NotificationItems</relationshipLabel>
    <relationshipName>NotificationItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Notification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Eq_Past_Due</fullName>
        <label>Eq Past Due</label>
    </customValue>
    <customValue>
        <fullName>Eq_Request</fullName>
        <label>Eq Request</label>
    </customValue>
    <masterLabel>Notification</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NotificationsTest.cls
@isTest
public without sharing class NotificationsTest {
    
  @testSetup static void setup() {

    Account testAccount1 = new Account();
    testAccount1.Name = 'My Test Account 1';
    insert testAccount1;

    Account testAccount2 = new Account();
    testAccount2.Name = 'My Test Account 2';
    insert testAccount2;

    Opportunity testOpp1 = new Opportunity();
    testOpp1.AccountId = testAccount1.Id;
    testOpp1.Name      = 'My Test Opp 1';
    testOpp1.StageName = 'Closed-Vendor Contract';
    testOpp1.CloseDate = Date.today();
    insert testOpp1;

    Opportunity testOpp2 = new Opportunity();
    testOpp2.AccountId = testAccount2.Id;
    testOpp2.Name      = 'My Test Opp 2';
    testOpp2.StageName = 'Closed-Vendor Contract';
    testOpp2.CloseDate = Date.today();
    insert testOpp2;

    Equipment__c testEq1 = new Equipment__c();
    testEq1.Name                  = 'My Test Eq 1';
    testEq1.Last_Visit_Date__c    = Date.today();
    testEq1.Opportunity__c        = testOpp1.Id;
    testEq1.Days_CAT1_Past_Due__c = 10;
    testEq1.Days_CAT5_Past_Due__c = 20;
    testEq1.Days_PM_Past_Due__c   = 30;
    insert testEq1;

    Equipment__c testEq2 = new Equipment__c();
    testEq2.Name                  = 'My Test Eq 2';
    testEq2.Last_Visit_Date__c    = Date.today();
    testEq2.Opportunity__c        = testOpp2.Id;
    testEq2.Days_CAT1_Past_Due__c = 10;
    testEq2.Days_CAT5_Past_Due__c = 20;
    testEq2.Days_PM_Past_Due__c   = 30;
    insert testEq2;

    Notification__c testMaster = new Notification__c();
    testMaster.Account__c          = testAccount1.Id;
    testMaster.NotificationType__c = 'Eq_Past_Due';
    testMaster.Max_Count__c        = 33;
    testMaster.Send_Count__c       = 0;
    testMaster.Date_First_Sent__c  = null;
    testMaster.Date_Last_Sent__c   = null;
    testMaster.User_Disabled__c    = false;
    insert testMaster;

    NotificationItem__c testDetail = new NotificationItem__c();
    testDetail.Equipment__c    = testEq1.Id;
    testDetail.Notification__c = testMaster.Id;
    insert testDetail;

  }

  @isTest
  public static void test1() {

    List<Notification__c> notificationList = [
      SELECT Account__c,Account__r.Name,Date_First_Sent__c,Date_Last_Sent__c,Id,Max_Count__c,Send_Count__c,NotificationType__c ,User_Disabled__c,
      (SELECT Equipment__c,Equipment__r.Vendor_Equipment_No__c FROM NotificationItems__r)
      FROM Notification__c 
      WHERE Max_Count__c = 33
      ORDER BY Account__r.Name, NotificationType__c, Date_Last_Sent__c Desc
    ];
    System.debug('notificationList');
    System.debug(notificationList);
    Notifications.equipmentNotifications();
  }

  @isTest
  public static void test2() {
    List<Account> accountList = [SELECT Id FROM Account      WHERE Name = 'My Test Account 2'];
    List<Equipment__c> eqList = [SELECT Id FROM Equipment__c WHERE Name = 'My Test Eq 2'];
    List<Id> eqIdList = new List<Id>();
    eqIdList.add(eqList[0].Id);
    Notifications.requestUpdate(accountList[0].Id, eqIdList);
  }

  @isTest
  public static void test3() {
    List<Account> accountList = [SELECT Id FROM Account      WHERE Name = 'My Test Account 1'];
    Id accId = accountList[0].Id;
    Notifications.getUpdates(accId,'Eq_Request');
  }

}