force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity is populated by class SchindlerOcrProcess if it can find a match on Contract Number.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Vendor Activities</relationshipLabel>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/ServiceHistory__c.object-meta.xml
<CustomObject>
    <label>Time Ticket</label>
    <nameField>
        <label>Time Ticket</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceHistory__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Time Tickets</relationshipLabel>
    <relationshipName>Time_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Service calls related to this opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Service_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoicePageControllerTest.cls
@isTest (SeeAllData=true)
public without sharing class InvoicePageControllerTest {

 @isTest
  public static void Test1(){ 
    List<ServiceHistory__c> data = InvoicePageController.getAllTimeTickets();
    Integer listLength = data.size();
    System.assertNotEquals(0, listLength);
  }

 @isTest
  public static void Test2(){ 
    List<Schindler_Invoice_History__c> data = InvoicePageController.getAllInvoices();
    Integer listLength = data.size();
    System.assertNotEquals(0, listLength);
  }

 @isTest
  public static void Test3(){ 
    List<Equipment__c> data = InvoicePageController.getAllEquipment();
    Integer listLength = data.size();
    System.assertNotEquals(0, listLength);

    String oppid = data[0].Opportunity__c;
    List<Equipment__c> data2 = InvoicePageController.getOpportunityEquipment(oppid);
    Integer listLength2 = data2.size();
    System.assertNotEquals(0, listLength2);

  }

 @isTest
  public static void Test4(){ 
    List<Schindler_Maintenance_Activity__c> data = InvoicePageController.getAllMaintenanceVisits();
    Integer listLength = data.size();
    System.assertNotEquals(0, listLength);
  }


}