force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Days_CAT1_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_CAT1_Past_Due__c</fullName>
    <label>Days CAT1 Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_CAT5_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_CAT5_Past_Due__c</fullName>
    <label>Days CAT5 Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_PM_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_PM_Past_Due__c</fullName>
    <label>Days PM Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <inlineHelpText>For Elev 01, Elev 02, - Elev 09 - Be sure to enter the 0 in front, so that it displays on CARE in chronological order.</inlineHelpText>
    <label>Display Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_30_Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_30_Day_Count__c</fullName>
    <label>Last 30 Day Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_PM_Date__c</fullName>
    <inlineHelpText>Last date where type = MNT</inlineHelpText>
    <label>Last PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Date__c</fullName>
    <label>Last Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Equipment_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Vendor&apos;s unique ID for this equipment.</inlineHelpText>
    <label>Vendor Equipment #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Visit_Count__c</fullName>
    <label>Record Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Notification master</description>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <formula>If(
   Or (
    User_Disabled__c = true,
    Send_Count__c = Max_Count__c
   ),
   false, 
   true
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Date_First_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_First_Sent__c</fullName>
    <label>Date First Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Date_Last_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Sent__c</fullName>
    <label>Date Last Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Max_Count__c.field-meta.xml
<CustomField>
    <fullName>Max_Count__c</fullName>
    <label>Max Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <label>NotificationType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Notification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Send_Count__c.field-meta.xml
<CustomField>
    <fullName>Send_Count__c</fullName>
    <label>Send Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/User_Disabled__c.field-meta.xml
<CustomField>
    <fullName>User_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NotificationItem__c/NotificationItem__c.object-meta.xml
<CustomObject>
    <label>NotificationItem</label>
    <nameField>
        <label>NotificationItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NotificationItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationItem__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>NotificationItems</relationshipLabel>
    <relationshipName>NotificationItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NotificationItem__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>NotificationItems</relationshipLabel>
    <relationshipName>NotificationItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Notification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Eq_Past_Due</fullName>
        <label>Eq Past Due</label>
    </customValue>
    <customValue>
        <fullName>Eq_Request</fullName>
        <label>Eq Request</label>
    </customValue>
    <masterLabel>Notification</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/notifications_eq_past_due_controller.cls
public without sharing class notifications_eq_past_due_controller {
  // For VisualForce email template controller
  public ID itemId {get; set;}
  public ID masterId {get; set;}
  public String accountName {get; set;}
  public String emailRecipient {get; set;}
  public String emailRecipientFN {get; set;}
  
  public notifications_eq_past_due_controller() {
  }

  public string getMyRequest() {
    if(emailRecipient == null) {
      return 'this is default request';
    } else {
      return 'return link for portal customer ' + emailRecipient;
    }
  }

  public List<NotificationItem__c> Notifications {
    get {
      Boolean returnEmpty = false;
      List<NotificationItem__c> notificationList;
      System.debug('get Notifications');
      if(itemId == null) {
        System.debug('itemId is null, returning empty list');
        returnEmpty = true;
      } else {
        System.debug('itemId is not null, returning list');
        System.debug(itemId);
        List<NotificationItem__c> masterList = [SELECT Notification__c FROM  NotificationItem__c WHERE Id = :itemId];
        NotificationItem__c masterRec = masterList[0];
        System.debug(masterRec.Notification__c);
        this.masterId = masterRec.Notification__c;
        System.debug('this.masterId:');
        System.debug(this.masterId);
        notificationList = [
          SELECT Notification__r.Account__c, Notification__r.Account__r.Name, Notification__r.Date_First_Sent__c, Notification__r.Date_Last_Sent__c, 
            Notification__r.Send_Count__c, Notification__r.NotificationType__c, Notification__r.User_Disabled__c, Notification__r.Id, Notification__r.Max_Count__c,
            Equipment__r.Days_CAT1_Past_Due__c,Equipment__r.Days_CAT5_Past_Due__c,Equipment__r.Days_PM_Past_Due__c,Equipment__r.Display_Name__c,
            Equipment__r.Last_30_Day_Count__c,Equipment__r.Last_PM_Date__c,Equipment__r.Last_Visit_Date__c,Equipment__r.Vendor_Equipment_No__c,Equipment__r.Visit_Count__c       
          FROM NotificationItem__c
          WHERE Notification__r.Current__c = true And Notification__r.Id = :this.masterId 
          ORDER BY Equipment__r.Display_Name__c          
        ];
        if(notificationList.size() > 0) {
          this.accountName = notificationList[0].notification__r.Account__r.Name;
        } else {
          returnEmpty = true; 
        }    
      }
      if(returnEmpty) {
        notificationList = new List<NotificationItem__c>();
        notificationList.add( new NotificationItem__c() );
      }
      return notificationList;
    }
    set;
  }

}