force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/State_Certificate_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Certificate_Expiration_Date__c</fullName>
    <label>State Certificate Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hydraulic</fullName>
            </value>
            <value>
                <fullName>Traction</fullName>
            </value>
            <value>
                <fullName>Geared</fullName>
            </value>
            <value>
                <fullName>Gearless</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Dumbwaiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Findings__c/Inspection_Findings__c.object-meta.xml
<CustomObject>
    <description>When a annual state write up is completed and violations are found, they will be stored in this object.</description>
    <label>Inspection Findings</label>
    <nameField>
        <label>Inspection Findings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Findings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Findings__c/fields/State_Inspection__c.field-meta.xml
<CustomField>
    <fullName>State_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State Inspection</label>
    <referenceTo>State_Inspection__c</referenceTo>
    <relationshipLabel>Inspection Findings</relationshipLabel>
    <relationshipName>Inspection_Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/CustomerStatus__c.field-meta.xml
<CustomField>
    <fullName>CustomerStatus__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Customer Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/UserStatus__c.field-meta.xml
<CustomField>
    <fullName>UserStatus__c</fullName>
    <inlineHelpText>External Status that is visible to Portal User</inlineHelpText>
    <label>User Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Awaiting User Action</fullName>
            </value>
            <value>
                <fullName>Renegotiate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Category 1</fullName>
            </value>
            <value>
                <fullName>Category 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Departure_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Departure_DateTime__c</fullName>
    <label>Departure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Vendor Activities</relationshipLabel>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Maintenance_Duration__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Duration__c</fullName>
    <formula>(Departure_DateTime__c -  Arrival_DateTime__c) * 24 * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>In minutes</inlineHelpText>
    <label>Maintenance Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <formula>(Arrival_DateTime__c - Call_Placed_DateTime__c ) * 24 * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>In minutes</inlineHelpText>
    <label>Response Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/State_Inspection__c/State_Inspection__c.object-meta.xml
<CustomObject>
    <label>State Inspection</label>
    <nameField>
        <label>State Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Inspection__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>State Inspections</relationshipLabel>
    <relationshipName>State_Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Inspection__c/fields/Inspection_Findings__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Findings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Findings</label>
    <referenceTo>Inspection_Findings__c</referenceTo>
    <relationshipLabel>State Inspections</relationshipLabel>
    <relationshipName>State_Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Inspection__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5YFIN</fullName>
            </value>
            <value>
                <fullName>5YISSUED</fullName>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>CORRECTIONS REQ</fullName>
                <label>Corrections Req</label>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>INCOMPLETE</fullName>
            </value>
            <value>
                <fullName>PASS</fullName>
            </value>
            <value>
                <fullName>PASS W/ COND</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>TEMPCERT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PortalInsightsController.cls
public without sharing class PortalInsightsController {

    @AuraEnabled
    public static InsightsWrapper getInsights(Id accountId) {

        return getInsights(accountId, Date.today().addYears(-5), Date.today());
    }

    public static InsightsWrapper getInsights(Id accountId, Date startDate, Date endDate) {

        InsightsWrapper result = new InsightsWrapper();

        // Load Activity Data
        Schindler_Maintenance_Activity__c[] maintenanceActivities = new Schindler_Maintenance_Activity__c[] {};
        Schindler_Maintenance_Activity__c[] callbackActivities = new Schindler_Maintenance_Activity__c[] {};
        Schindler_Maintenance_Activity__c[] testingActivities = new Schindler_Maintenance_Activity__c[] {};
        Schindler_Maintenance_Activity__c[] activities = PortalController.getActivities(accountId, startDate, endDate);

        Integer maintenanceTasksQuantity = 0;
        Decimal maintenanceDuration = 0;
        Decimal responseTime = 0;

        for (Schindler_Maintenance_Activity__c activity :activities) {

            if (PortalConstants.TESTING_TYPE.equalsIgnoreCase(activity.Type__c)) {
                // maintenanceActivities.add(activity);

                if (PortalConstants.CATEGORY_1.equalsIgnoreCase(activity.Category__c)) {

                    if (activity.Departure_DateTime__c != null) {
                        result.category1.firstAmount ++;
                    }
                    else {
                        result.category1.secondAmount ++;
                    }
                }
                else if (PortalConstants.CATEGORY_5.equalsIgnoreCase(activity.Category__c)) {

                    if (activity.Departure_DateTime__c != null) {
                        result.category5.firstAmount ++;
                    }
                    else {
                        result.category5.secondAmount ++;
                    }
                }
            }
            else if (PortalConstants.MAINTENANCE_TYPE.equalsIgnoreCase(activity.Type__c)) {
                // testingActivities.add(activity);

                maintenanceTasksQuantity ++;
                responseTime += activity.Response_Time__c != null ? activity.Response_Time__c : 0;
                maintenanceDuration += activity.Maintenance_Duration__c != null ? activity.Maintenance_Duration__c : 0;

                if (activity.Departure_DateTime__c != null) {
                    result.maintenance.firstAmount ++;
                }
                else {
                    result.maintenance.secondAmount ++;
                }
            }
            else if (PortalConstants.CALLBACK_TYPE.equalsIgnoreCase(activity.Type__c)) {
                // callbackActivities.add(activity);
                result.callbacks ++;
            }
        }

        result.maintenance.firstAmountLabel = 'Completed';
        result.maintenance.secondAmountLabel = 'Not Completed';
        result.category1.firstAmountLabel = 'Completed';
        result.category1.secondAmountLabel = 'Not Completed';
        result.category5.firstAmountLabel = 'Completed';
        result.category5.secondAmountLabel = 'Not Completed';

        if (maintenanceTasksQuantity > 0) {
            result.responseAverage = (responseTime / maintenanceTasksQuantity).intValue();
            result.maintenanceAverage = (maintenanceDuration / maintenanceTasksQuantity).intValue();
        }

        // Load Invoice Data
        Schindler_Invoice_History__c[] invoices = PortalController.getInvoices(null, accountId);

        Integer acceptedInvoicesQuantity = 0;
        Integer disputedInvoicesQuantity = 0;
        Integer openInvoicesQuantity = 0;

        for (Schindler_Invoice_History__c invoiceRecord :invoices) {

            result.totalBilledInvoices.total += invoiceRecord.Invoice_Total__c != null ? invoiceRecord.Invoice_Total__c : 0;

            if (PortalConstants.PAY_STATUS.equalsIgnoreCase(invoiceRecord.UserStatus__c)) {
                acceptedInvoicesQuantity ++;
            }
            else if (PortalConstants.DISPUTE_STATUS.equalsIgnoreCase(invoiceRecord.UserStatus__c)) {
                disputedInvoicesQuantity ++;
            }
            else {
                openInvoicesQuantity ++;
            }
        }

        result.totalBilledInvoices.firstAmount = openInvoicesQuantity;
        result.totalBilledInvoices.firstAmountLabel = 'Open';
        result.totalBilledInvoices.secondAmount = disputedInvoicesQuantity;
        result.totalBilledInvoices.secondAmountLabel = 'Disputed';
        result.totalBilledInvoices.thirdAmount = acceptedInvoicesQuantity;
        result.totalBilledInvoices.thirdAmountLabel = 'Accepted';

        // Load Proposal Data
        Proposal__c[] proposals = PortalController.getProposalsHistory(accountId);

        Integer openProposalsQuantity = 0;
        Integer acceptedProposalsQuantity = 0;
        Integer declinedProposalsQuantity = 0;

        for (Proposal__c proposalRecord :proposals) {

            result.totalProposedRepairs.total += proposalRecord.Price__c != null ? proposalRecord.Price__c : 0;

            if (PortalConstants.ACCEPTED_STATUS.equalsIgnoreCase(proposalRecord.CustomerStatus__c)) {
                acceptedProposalsQuantity ++;
            }
            else if (PortalConstants.DECLINED_STATUS.equalsIgnoreCase(proposalRecord.CustomerStatus__c)) {
                declinedProposalsQuantity ++;
            }
            else {
                openProposalsQuantity ++;
            }
        }

        result.totalProposedRepairs.firstAmount = openProposalsQuantity;
        result.totalProposedRepairs.firstAmountLabel = 'Open';
        result.totalProposedRepairs.secondAmount = declinedProposalsQuantity;
        result.totalProposedRepairs.secondAmountLabel = 'Declined';
        result.totalProposedRepairs.thirdAmount = acceptedProposalsQuantity;
        result.totalProposedRepairs.thirdAmountLabel = 'Accepted';

        //Load Certificates
        Equipment__c[] equipments = PortalController.getUnits(null, accountId);

        Integer expiredCertificatesQuantity = 0;
        Integer activeCertificatesQuantity = 0;

        for (Equipment__c equipmentRecord :equipments) {

            if (equipmentRecord.State_Certificate_Expiration_Date__c != null && equipmentRecord.State_Certificate_Expiration_Date__c < Date.today()) {
                expiredCertificatesQuantity ++;
            }
            else {
                activeCertificatesQuantity ++;
            }
        }

        result.certificates.firstAmount = activeCertificatesQuantity;
        result.certificates.firstAmountLabel = 'Active';
        result.certificates.secondAmount = expiredCertificatesQuantity;
        result.certificates.secondAmountLabel = 'Expired';

        // Load State Records with Inspections
        State_Inspection__c[] inspections = PortalController.getStateRecordsWithInspections(null, accountId);

        Integer averageViolations = 0;
        Integer passedInspections = 0;
        Integer incompleteInspections = 0;
        Integer failedInspections = 0;

        for (State_Inspection__c inspectionRecord :inspections) {

            if (inspectionRecord.Inspection_Findings__r != null) {
                averageViolations += inspectionRecord.Inspection_Findings__r.size();
            }

            if (PortalConstants.INSPECTION_PASS.equalsIgnoreCase(inspectionRecord.Result__c) ||
                PortalConstants.INSPECTION_PASS_CONDITIONS.equalsIgnoreCase(inspectionRecord.Result__c)) {

                passedInspections ++;
            }
            else if (PortalConstants.INSPECTION_INCOMPLETE.equalsIgnoreCase(inspectionRecord.Result__c)) {

                incompleteInspections ++;
            }
            else if (PortalConstants.INSPECTION_FAIL.equalsIgnoreCase(inspectionRecord.Result__c)) {

                failedInspections ++;
            }
        }

        result.stateInspectionReports.firstAmount = passedInspections;
        result.stateInspectionReports.firstAmountLabel = 'Passed';
        result.stateInspectionReports.secondAmount = incompleteInspections;
        result.stateInspectionReports.secondAmountLabel = 'Incomplete';
        result.stateInspectionReports.thirdAmount = failedInspections;
        result.stateInspectionReports.thirdAmountLabel = 'Failed';

        if (!inspections.isEmpty()) {
            result.violationAverage = averageViolations / inspections.size();
        }

        return result;
    }

    public class InsightsWrapper {

        @AuraEnabled
        public InsightsChartWrapper maintenance {get; set;}

        @AuraEnabled
        public InsightsChartWrapper category1 {get; set;}

        @AuraEnabled
        public InsightsChartWrapper category5 {get; set;}

        @AuraEnabled
        public Integer maintenanceAverage {get; set;}

        @AuraEnabled
        public Integer responseAverage {get; set;}

        @AuraEnabled
        public Integer callbacks {get; set;}

        @AuraEnabled
        public Decimal violationAverage {get; set;}

        @AuraEnabled
        public InsightsChartWrapper totalContractSpending {get; set;}

        @AuraEnabled
        public InsightsChartWrapper totalBilledInvoices {get; set;}

        @AuraEnabled
        public InsightsChartWrapper totalProposedRepairs {get; set;}

        @AuraEnabled
        public InsightsChartWrapper stateInspectionReports {get; set;}

        @AuraEnabled
        public InsightsChartWrapper certificates {get; set;}

        public InsightsWrapper() {
            callbacks = 0;
            responseAverage = 0;
            maintenanceAverage = 0;
            violationAverage = 0;

            maintenance = new InsightsChartWrapper();
            category1 = new InsightsChartWrapper();
            category5 = new InsightsChartWrapper();

            totalBilledInvoices = new InsightsChartWrapper();
            certificates = new InsightsChartWrapper();
            stateInspectionReports = new InsightsChartWrapper();
            totalProposedRepairs = new InsightsChartWrapper();
        }
    }

    public class InsightsChartWrapper {

        @AuraEnabled
        public Decimal firstAmount {get; set;}

        @AuraEnabled
        public Decimal secondAmount {get; set;}

        @AuraEnabled
        public Decimal thirdAmount {get; set;}

        @AuraEnabled
        public Decimal total {get; set;}

        @AuraEnabled
        public String firstAmountLabel {get; set;}

        @AuraEnabled
        public String secondAmountLabel {get; set;}

        @AuraEnabled
        public String thirdAmountLabel {get; set;}

        public InsightsChartWrapper() {

            firstAmount = 0;
            secondAmount = 0;
            thirdAmount = 0;
            total = 0;
        }
    }
}