force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Cat1_Count__c.field-meta.xml
<CustomField>
    <fullName>Cat1_Count__c</fullName>
    <label>Cat1 Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Cat5_Count__c.field-meta.xml
<CustomField>
    <fullName>Cat5_Count__c</fullName>
    <label>Cat5 Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passenger Elevator</fullName>
            </value>
            <value>
                <fullName>Freight Elevator</fullName>
            </value>
            <value>
                <fullName>Escalator</fullName>
            </value>
            <value>
                <fullName>Moving Walks</fullName>
            </value>
            <value>
                <fullName>Dumbwaiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Controller_Type__c.field-meta.xml
<CustomField>
    <fullName>Controller_Type__c</fullName>
    <label>Controller</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Controller_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Days_PM_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_PM_Past_Due__c</fullName>
    <label>Days PM Past Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <inlineHelpText>For Elev 01, Elev 02, - Elev 09 - Be sure to enter the 0 in front, so that it displays on CARE in chronological order.</inlineHelpText>
    <label>Display Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Inspection_Witness__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Witness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection Witness</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_12_Month_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_12_Month_Count__c</fullName>
    <label>Last 12 Month Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_30_Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_30_Day_Count__c</fullName>
    <label>Last 30 Day Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Cat1_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Cat1_Date__c</fullName>
    <label>Last Cat1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Cat5_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Cat5_Date__c</fullName>
    <label>Last Cat5 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Cleandown_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Cleandown_Date__c</fullName>
    <label>Last Cleandown Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Index_Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Index_Test_Date__c</fullName>
    <label>Last Index Test Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_PM_Date__c</fullName>
    <inlineHelpText>Last date where type = MNT</inlineHelpText>
    <label>Last PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Date__c</fullName>
    <label>Last Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Last_Visit_Reason__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Reason__c</fullName>
    <label>Last Visit Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Load_Lb__c.field-meta.xml
<CustomField>
    <fullName>Load_Lb__c</fullName>
    <inlineHelpText>Load in pounds (Lds) e.g. 5,000</inlineHelpText>
    <label>Load (Lb)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_Cat1_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Cat1_Date__c</fullName>
    <label>Next Cat1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_Cat5_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Cat5_Date__c</fullName>
    <label>Next Cat5 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_Cleandown_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Cleandown_Date__c</fullName>
    <label>Next Cleandown Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_Index_Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Index_Test_Date__c</fullName>
    <label>Next Index Test Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Next_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_PM_Date__c</fullName>
    <label>Next PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Remote_Monitoring__c.field-meta.xml
<CustomField>
    <fullName>Remote_Monitoring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Monitoring</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <inlineHelpText>Speed in feet/min e.g.150</inlineHelpText>
    <label>Speed (f/min)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Certificate_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Certificate_Expiration_Date__c</fullName>
    <label>State Certificate Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Certificate_First_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Certificate_First_Issue_Date__c</fullName>
    <description>When the equipment was born.</description>
    <inlineHelpText>When the equipment was born.</inlineHelpText>
    <label>State Certificate First Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Certificate_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>State_Certificate_Issue_Date__c</fullName>
    <label>State Certificate Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Elevator_Subtype__c.field-meta.xml
<CustomField>
    <fullName>State_Elevator_Subtype__c</fullName>
    <label>Elevator Subtype</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Elevator_Type__c.field-meta.xml
<CustomField>
    <fullName>State_Elevator_Type__c</fullName>
    <label>Elevator Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_ID__c.field-meta.xml
<CustomField>
    <fullName>State_ID__c</fullName>
    <description>Municipality equipment id number.</description>
    <inlineHelpText>Municipality equipment id number. Could also be: License #, State ID, or Certificate.</inlineHelpText>
    <label>Conveyance ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Location_City__c.field-meta.xml
<CustomField>
    <fullName>State_Location_City__c</fullName>
    <label>Location City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Location_Description__c.field-meta.xml
<CustomField>
    <fullName>State_Location_Description__c</fullName>
    <label>Location Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Location_Street__c.field-meta.xml
<CustomField>
    <fullName>State_Location_Street__c</fullName>
    <label>Location Street</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Location_Zip__c.field-meta.xml
<CustomField>
    <fullName>State_Location_Zip__c</fullName>
    <label>Location Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Owner_Name__c</fullName>
    <label>State-Owner Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Region__c.field-meta.xml
<CustomField>
    <fullName>State_Region__c</fullName>
    <label>State-Region</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>State_Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/State_Status__c.field-meta.xml
<CustomField>
    <fullName>State_Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Stops__c.field-meta.xml
<CustomField>
    <fullName>Stops__c</fullName>
    <label>Stops</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hydraulic</fullName>
            </value>
            <value>
                <fullName>Traction</fullName>
            </value>
            <value>
                <fullName>Geared</fullName>
            </value>
            <value>
                <fullName>Gearless</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Dumbwaiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor_Equipment_No__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Vendor&apos;s unique ID for this equipment.</inlineHelpText>
    <label>Vendor Equipment #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Visit_Count__c</fullName>
    <label>Record Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_test_covered__c.field-meta.xml
<CustomField>
    <fullName>Annual_test_covered__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does vendor contract include Annual Test?</inlineHelpText>
    <label>Annual test covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/year5_test_covered__c.field-meta.xml
<CustomField>
    <fullName>year5_test_covered__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does vendor contract include 5 year test?</inlineHelpText>
    <label>5 year test covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Vendor Activities</relationshipLabel>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Controller_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dover Composite</fullName>
    </customValue>
    <customValue>
        <fullName>Dover DMC</fullName>
    </customValue>
    <customValue>
        <fullName>Dover Oildraulic</fullName>
    </customValue>
    <customValue>
        <fullName>Otis B Series Controls</fullName>
    </customValue>
    <customValue>
        <fullName>Otis Gen II</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler 300A</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler 3300</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler 330A</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler 400A</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler 5500</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler Miconic A</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler Miconic TX-R5</fullName>
    </customValue>
    <customValue>
        <fullName>Schindler Miconic TX-RS</fullName>
    </customValue>
    <customValue>
        <fullName>Thyssen TAC20</fullName>
    </customValue>
    <customValue>
        <fullName>Thyssen Tac32</fullName>
        <label>Thyssen TAC32</label>
    </customValue>
    <customValue>
        <fullName>Thyssen TAC 50</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown model</fullName>
    </customValue>
    <customValue>
        <fullName>Westinghouse MPH2</fullName>
    </customValue>
    <masterLabel>Controller Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PortalControllerHelper.cls
public without sharing class PortalControllerHelper {

    public static Equipment__c[] getUnits(Id accountId) {

        Equipment__c[] result = new Equipment__c[] {};

        for (Equipment__c record :[SELECT
                                        Cat1_Count__c,
                                        Cat5_Count__c,
                                        Class__c,
                                        Controller_Type__c,
                                        Display_Name__c,
                                        Inspection_Witness__c,
                                        Last_12_Month_Count__c,
                                        Last_30_Day_Count__c,
                                        Last_Cat1_Date__c,
                                        Last_Cat5_Date__c,
                                        Last_Cleandown_Date__c,
                                        Last_Index_Test_Date__c,
                                        Last_PM_Date__c,
                                        Last_Visit_Date__c,
                                        Last_Visit_Reason__c,
                                        Load_Lb__c,
                                        Name,
                                        Next_Cat1_Date__c,
                                        Next_Cat5_Date__c,
                                        Next_Cleandown_Date__c,
                                        Next_Index_Test_Date__c,
                                        Next_PM_Date__c,
                                        Opportunity__c,
                                        Remote_Monitoring__c,
                                        Speed__c,
                                        State_Certificate_Expiration_Date__c,
                                        State_Certificate_First_Issue_Date__c,
                                        State_Certificate_Issue_Date__c,
                                        State_Elevator_Subtype__c,
                                        State_Elevator_Type__c,
                                        State_ID__c,
                                        State_Location_City__c,
                                        State_Location_Description__c,
                                        State_Location_Street__c,
                                        State_Location_Zip__c,
                                        State_Owner_Name__c,
                                        State_Region__c,
                                        State_Serial_Number__c,
                                        State_Status__c,
                                        Stops__c,
                                        Type__c,
                                        Vendor_Equipment_No__c,
                                        Visit_Count__c,
                                        Days_PM_Past_Due__c,

                                        Opportunity__r.year5_test_covered__c,
                                        Opportunity__r.Annual_test_covered__c

                                    FROM Equipment__c
                                    WHERE Opportunity__r.accountId = :accountId
                                    ORDER BY Display_Name__c])
        {
            // Enclosing parenthesis this way to avoid breaking the VSC formatting
            result.Add(record);
        }

        return result;
    }

    public static PortalEquipmentWrapper[] getEquipmentWrappers(Equipment__c[] equipments, Schindler_Maintenance_Activity__c[] activities) {

        return getEquipmentWrappers(equipments, activities, true);
    }

    public static PortalEquipmentWrapper[] getEquipmentWrappers(Equipment__c[] equipments, Schindler_Maintenance_Activity__c[] activities, Boolean hasBreak) {

        PortalEquipmentWrapper[] result = new PortalEquipmentWrapper[] {};

        for (Equipment__c equipment :equipments) {

            for (Schindler_Maintenance_Activity__c activity :activities) {

                if (equipment.Id == activity.Equipment__c) {
                    result.add(new PortalEquipmentWrapper(equipment, activity));

                    if (hasBreak) {
                        break;
                    }
                }
            }
        }

        return result;
    }

}