force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/Schindler_Invoice_History__c.object-meta.xml
<CustomObject>
    <description>History of Schindler Invoices</description>
    <label>Invoice History</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Invoice_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity is populated by class SchindlerOcrProcess if it can find a match on Contract Number.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Invoice_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Vendor Activities</relationshipLabel>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Schindler_Maintenance_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerPortalControllerTest.cls
@IsTest (SeeAllData=true)
public with sharing class CustomerPortalControllerTest {

  @IsTest public static void Test1() {
    List<Account> data = CustomerPortalController.getAccounts();
    System.assertNotEquals(0, data.size());
  }

  @IsTest public static void Test2() {
    List<Equipment__c> eqList = [SELECT  Opportunity__r.AccountId FROM Equipment__c WHERE Opportunity__r.AccountId != null LIMIT 1];
    String acctId = eqList[0].Opportunity__r.AccountId;
    List<Equipment__c> data = CustomerPortalController.getAccountEquipment(acctId);
    System.assertNotEquals(0, data.size());
  }

  @IsTest public static void Test3() {
    List<Schindler_Invoice_History__c> invList = [SELECT  Opportunity__r.AccountId FROM Schindler_Invoice_History__c  WHERE Opportunity__r.AccountId  != null LIMIT 1]; 
    String acctId = invList[0].Opportunity__r.AccountId;
    List<Schindler_Invoice_History__c> data = CustomerPortalController.getAccountInvoices(acctId);
    System.assertNotEquals(0, data.size());
  }

  @IsTest public static void Test4() {
    List<Schindler_Maintenance_Activity__c> maintList = [SELECT  Opportunity__r.AccountId FROM Schindler_Maintenance_Activity__c  WHERE Opportunity__r.AccountId  != null LIMIT 1]; 
    String acctId = maintList[0].Opportunity__r.AccountId;
    List<Schindler_Maintenance_Activity__c> data = CustomerPortalController.getAccountMaintenance(acctId);
    System.assertNotEquals(0, data.size());
  }

}