force-app/main/default/objects/Schindler_Maintenance_Activity__c/Schindler_Maintenance_Activity__c.object-meta.xml
<CustomObject>
    <label>Vendor Activities</label>
    <nameField>
        <label>Vendor Activities</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Arrival_date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_date__c</fullName>
    <label>Arrival date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Arrival_time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_time__c</fullName>
    <label>Arrival time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Call_placed_date__c.field-meta.xml
<CustomField>
    <fullName>Call_placed_date__c</fullName>
    <label>Call placed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Call_placed_time__c.field-meta.xml
<CustomField>
    <fullName>Call_placed_time__c</fullName>
    <label>Call placed time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Closed_date__c.field-meta.xml
<CustomField>
    <fullName>Closed_date__c</fullName>
    <label>Departure date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Closed_time__c.field-meta.xml
<CustomField>
    <fullName>Closed_time__c</fullName>
    <label>Departure time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Dispatched_date__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_date__c</fullName>
    <label>Dispatched date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/Dispatched_time__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_time__c</fullName>
    <label>Dispatched time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/EquipNo__c.field-meta.xml
<CustomField>
    <fullName>EquipNo__c</fullName>
    <label>EquipNo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/JobID__c.field-meta.xml
<CustomField>
    <fullName>JobID__c</fullName>
    <label>JobID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schindler_Maintenance_Activity__c/fields/VisitDate__c.field-meta.xml
<CustomField>
    <fullName>VisitDate__c</fullName>
    <label>VisitDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MaintenanceHistoryTriggerTest.cls
@isTest (SeeAllData=true)
public with sharing class MaintenanceHistoryTriggerTest {

  @isTest (SeeAllData=true)
  public static void test1() {
    Date today = Date.today();
    Schindler_Maintenance_Activity__c sma = new Schindler_Maintenance_Activity__c();
    sma.Call_placed_date__c = today;
    sma.Dispatched_date__c  = today;
    sma.Arrival_date__c     = today;
    sma.Closed_date__c      = today;
    sma.Call_placed_time__c = '9:20 AM';
    sma.Dispatched_time__c  = '10:40 AM';
    sma.Arrival_time__c     = '11:01 AM';
    sma.Closed_time__c      = '4:23 PM';
    sma.EquipNo__c          = 'S1452462';
    sma.JobID__c            = '67740594';
    sma.Name                = 'Test';
    sma.Type__c             = 'MNT';
    sma.VisitDate__c        = today;

    insert sma;
    System.debug(sma.id);
  }


}