force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Customer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comments__c</fullName>
    <label>Customer Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/CustomerStatus__c.field-meta.xml
<CustomField>
    <fullName>CustomerStatus__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Customer Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PortalProposalController.cls
public without sharing class PortalProposalController {

    @AuraEnabled
    public static void acceptProposal(Id proposalId, String message) {

        Proposal__c record = new Proposal__c(Id = proposalId);
        record.Customer_Comments__c = message;
        record.CustomerStatus__c = 'Accepted';
        update record;
    }

    @AuraEnabled
    public static void declineProposal(Id proposalId, String message) {

        Proposal__c record = new Proposal__c(Id = proposalId);
        record.Customer_Comments__c = message;
        record.CustomerStatus__c = 'Declined';
        update record;
    }
}