force-app/main/default/objects/Opportunity/fields/Annual_test_covered__c.field-meta.xml
<CustomField>
    <fullName>Annual_test_covered__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does vendor contract include Annual Test?</inlineHelpText>
    <label>Annual test covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Annual_test_date__c.field-meta.xml
<CustomField>
    <fullName>Annual_test_date__c</fullName>
    <label>Annual test date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commitment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Commitment_Terms__c</fullName>
    <label>Commitment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Unit</fullName>
            </value>
            <value>
                <fullName>Per Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CoverageHours__c.field-meta.xml
<CustomField>
    <fullName>CoverageHours__c</fullName>
    <description>IF( MOD( HOUR(Coverage_end_time__c ) - HOUR(Coverage_start_time__c), 24 ) &lt; 1, &quot;&quot;, TEXT( MOD( HOUR(Coverage_end_time__c ) - HOUR(Coverage_start_time__c), 24 ) ) &amp; 
IF((MOD( HOUR(Coverage_end_time__c ) - HOUR(Coverage_start_time__c), 24 )) = 1, &quot; HR &quot;, &quot; HRS &quot; ) ) 
&amp; IF( (ROUND( MOD( Minute(Coverage_end_time__c ) - Minute(Coverage_start_time__c), 60 ), 0 )) = 0, &quot;&quot;, TEXT( ROUND( MOD( Minute(Coverage_end_time__c ) - Minute(Coverage_start_time__c), 60 ), 0 ) ) &amp; &quot; MINS&quot; )</description>
    <formula>TEXT(Coverage_Hours__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CoverageHours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <inlineHelpText>End date of contract between the Elevator Vendor and their client.</inlineHelpText>
    <label>Expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency_of_service__c.field-meta.xml
<CustomField>
    <fullName>Frequency_of_service__c</fullName>
    <label>Frequency of service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Bi-Annually</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Periodically</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hourly_requirement__c.field-meta.xml
<CustomField>
    <fullName>Hourly_requirement__c</fullName>
    <label>Hourly requirement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unspecified</fullName>
                <default>true</default>
                <label>Unspecified</label>
            </value>
            <value>
                <fullName>0 hours</fullName>
            </value>
            <value>
                <fullName>1 hour per month</fullName>
            </value>
            <value>
                <fullName>2 hours per month</fullName>
            </value>
            <value>
                <fullName>3 hours per month</fullName>
            </value>
            <value>
                <fullName>4 hours per month</fullName>
            </value>
            <value>
                <fullName>5 hours per month</fullName>
            </value>
            <value>
                <fullName>6 hours per month</fullName>
            </value>
            <value>
                <fullName>7 hour per month</fullName>
            </value>
            <value>
                <fullName>8 hours per month</fullName>
            </value>
            <value>
                <fullName>9 hours per month</fullName>
            </value>
            <value>
                <fullName>10 hours per month</fullName>
            </value>
            <value>
                <fullName>1 hour per quarter</fullName>
            </value>
            <value>
                <fullName>2 hours per quarter</fullName>
            </value>
            <value>
                <fullName>3 hours per quarter</fullName>
            </value>
            <value>
                <fullName>4 hours per quarter</fullName>
            </value>
            <value>
                <fullName>5 hours per quarter</fullName>
            </value>
            <value>
                <fullName>6 hours per quarter</fullName>
            </value>
            <value>
                <fullName>7 hour per quarter</fullName>
            </value>
            <value>
                <fullName>8 hours per quarter</fullName>
            </value>
            <value>
                <fullName>9 hours per quarter</fullName>
            </value>
            <value>
                <fullName>10 hours per quarter</fullName>
            </value>
            <value>
                <fullName>1 hour every 6 months</fullName>
            </value>
            <value>
                <fullName>2 hours every 6 months</fullName>
            </value>
            <value>
                <fullName>3 hours every 6 months</fullName>
            </value>
            <value>
                <fullName>4 hours every 6 months</fullName>
            </value>
            <value>
                <fullName>5 hours every 6 months</fullName>
            </value>
            <value>
                <fullName>6 hours every 6 months</fullName>
            </value>
            <value>
                <fullName>7 hour every 6 months</fullName>
            </value>
            <value>
                <fullName>8 hours every 6 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start date of contract between Elevator vendor and their client</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contract_Number__c</fullName>
    <inlineHelpText>Vendor&apos;s contract Number, also known as Customer Number.  Schindler data seems to label the same field two ways.</inlineHelpText>
    <label>Vendor Contract Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/year5_test_covered__c.field-meta.xml
<CustomField>
    <fullName>year5_test_covered__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does vendor contract include 5 year test?</inlineHelpText>
    <label>5 year test covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/year5_test_date__c.field-meta.xml
<CustomField>
    <fullName>year5_test_date__c</fullName>
    <label>5 year test date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/ServiceHistory__c.object-meta.xml
<CustomObject>
    <label>Time Ticket</label>
    <nameField>
        <label>Time Ticket</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceHistory__c/fields/Building_NameAddress__c.field-meta.xml
<CustomField>
    <fullName>Building_NameAddress__c</fullName>
    <label>Building Name/Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Doubletime_Onsite_time__c.field-meta.xml
<CustomField>
    <fullName>Doubletime_Onsite_time__c</fullName>
    <label>Overtime 2x Onsite time</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Doubletime_Travel_time__c.field-meta.xml
<CustomField>
    <fullName>Doubletime_Travel_time__c</fullName>
    <label>Overtime 2x Travel time</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Service calls related to this opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Service_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Overtime_Onsite_time__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Onsite_time__c</fullName>
    <label>Overtime Onsite time</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Overtime_Travel_time__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Travel_time__c</fullName>
    <label>Overtime Travel time</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Problem_reported__c.field-meta.xml
<CustomField>
    <fullName>Problem_reported__c</fullName>
    <label>Problem reported</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Repoted_By__c.field-meta.xml
<CustomField>
    <fullName>Repoted_By__c</fullName>
    <label>Repoted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Service_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Report_Date__c</fullName>
    <label>Service Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Standard_Onsite_time__c.field-meta.xml
<CustomField>
    <fullName>Standard_Onsite_time__c</fullName>
    <label>Standard Onsite time</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Standard_Travel_time__c.field-meta.xml
<CustomField>
    <fullName>Standard_Travel_time__c</fullName>
    <label>Standard Travel time</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <label>Technician</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Technician_Arrival_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Technician_Arrival_DateTime__c</fullName>
    <label>Technician Arrival DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Technician_Departure_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Technician_Departure_DateTime__c</fullName>
    <label>Technician Departure DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Time_unit_returned_to_service__c.field-meta.xml
<CustomField>
    <fullName>Time_unit_returned_to_service__c</fullName>
    <label>Time unit returned to service</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Vendor_Building_ID__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Building_ID__c</fullName>
    <label>Vendor Building ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Vendor_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contract_Number__c</fullName>
    <label>Vendor Contract Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Vendor_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Equipment__c</fullName>
    <label>Vendor Equipment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Vendor_Notification__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Notification__c</fullName>
    <label>Vendor Notification</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Vendor_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Sales_Order__c</fullName>
    <label>Vendor Sales Order</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Vendor_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Work_Order__c</fullName>
    <label>Vendor Work Order</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceHistory__c/fields/Work_description__c.field-meta.xml
<CustomField>
    <fullName>Work_description__c</fullName>
    <label>Work description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/opportunityController.cls
public with sharing class opportunityController {

  @AuraEnabled(cacheable=true)
  public static List<Opportunity> getServiceData(Id id) {
    List<Opportunity> data = [SELECT Id,Name,Start_Date__c, Expiration_date__c,Frequency_of_service__c,Hourly_requirement__c,Annual_test_covered__c,Annual_test_date__c,Commitment_Terms__c,CoverageHours__c,year5_test_covered__c,year5_test_date__c, AccountId,
      (SELECT Building_NameAddress__c,Doubletime_Onsite_time__c,Doubletime_Travel_time__c,Id,Name,Opportunity__c,Overtime_Onsite_time__c,Overtime_Travel_time__c,OwnerId,Problem_reported__c,Repoted_By__c,Service_Report_Date__c,Standard_Onsite_time__c,Standard_Travel_time__c,Status__c,Technician__c,Technician_Arrival_DateTime__c,Technician_Departure_DateTime__c,Time_unit_returned_to_service__c,Vendor_Building_ID__c,Vendor_Contract_Number__c,Vendor_Equipment__c,Vendor_Notification__c,Vendor_Sales_Order__c,Vendor_Work_Order__c,Work_description__c FROM Service_Histories__r ORDER BY Service_Report_Date__c DESC)
       FROM Opportunity Where Id = :id];
    System.debug(data);
    return data;
  }

}