force-app/main/default/objects/OCR_Send_Log__c/OCR_Send_Log__c.object-meta.xml
<CustomObject>
    <description>Log of files with their MD5 checksums that are due for OCR processing</description>
    <label>OCR Send Log</label>
    <nameField>
        <label>OCR Send Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Send Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCR_Send_Log__c/fields/Resend__c.field-meta.xml
<CustomField>
    <fullName>Resend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsent</fullName>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>File Title</description>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OcrBatchHelper.cls
public without sharing class OcrBatchHelper implements Schedulable {  

  // This is scheduled to run every 5 minutes.

  public void execute(SchedulableContext SC) {

  //  Integer currentBatchCount = AuditmateUtility.getIntVal('OcrBatchCount');
  //  if(currentBatchCount < 30 ) {
    Map<Id,OCR_Send_Log__c> ocrLogMap;

    if(Test.isRunningTest()) { 
      ocrLogMap = new Map<Id,OCR_Send_Log__c>([
        SELECT Id, PdfVersionId__c, Title__c,Resend__c, Status__c,Result__c  
        From OCR_Send_Log__c  WHERE (Status__c = 'Unsent' OR Resend__c = true) AND Result__c != 'Errors!' LIMIT 1
      ]);
    } else {
      ocrLogMap = new Map<Id,OCR_Send_Log__c>([
        SELECT Id, PdfVersionId__c, Title__c,Resend__c, Status__c,Result__c  
        From OCR_Send_Log__c  WHERE (Status__c = 'Unsent' OR Resend__c = true) AND Result__c != 'Errors!' LIMIT 9
      ]);
    }
  
      Integer mapSize = ocrLogMap.size();
      if(mapSize > 0) {
        Id batchInstanceId = Database.executeBatch(new OcrBatch(ocrLogMap));
        System.debug('OcrBatchHelper Found ' + mapSize.format() + ' records in OCR_Send_Log__c to be sent to OCR.');
        System.debug('OcrBatch started.  Job Id:');
        System.debug(batchInstanceId);
      } else {
        System.debug(datetime.now().format('yyyy.MM.dd HH:mm:ss z') + ' OcrBatchHelper did not see any unsent records in OCR_Send_Log__c.');
      }
  //  } else {
  //    System.debug('OcrBatchHelper sees currentBatchCount = ' + currentBatchCount.format());
  //    System.debug('OcrBatchHelper is not launching OcrBatch at this time');
  //  }
  }
}