force-app/main/default/objects/OCR_Send_Log__c/OCR_Send_Log__c.object-meta.xml
<CustomObject>
    <description>Log of files with their MD5 checksums that are due for OCR processing</description>
    <label>OCR Send Log</label>
    <nameField>
        <label>OCR Send Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Send Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCR_Send_Log__c/fields/JsonVersionId__c.field-meta.xml
<CustomField>
    <fullName>JsonVersionId__c</fullName>
    <label>JsonVersionId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Staged__c.field-meta.xml
<CustomField>
    <fullName>Staged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsent</fullName>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>File Title</description>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OcrBatchStaging.cls
public without sharing class OcrBatchStaging implements Database.Batchable<sObject> {

  public Database.QueryLocator start(Database.BatchableContext BC) {
      // Note: Using limit of 5
      // AuditmateUtility.incIntVal('OcrBatchCount');
      String sQuery = 'SELECT Id,JsonVersionId__c,Staged__c,Status__c,Title__c FROM OCR_Send_Log__c WHERE Status__c = \'Sent\' AND Staged__c = false AND Result__c != \'Errors!\' LIMIT 5';
      System.debug(sQuery);
      // Integer currentBatchCount = AuditmateUtility.getIntVal('OcrBatchCount');
      // System.debug('OcrBatchStaging currentBatchCount ' + currentBatchCount.format() );
      return Database.getQueryLocator(sQuery);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
      List<OCR_Send_Log__c> ocrUpdateList = new List<OCR_Send_Log__c>();
      String result;
      Integer count = 0;
      for (sObject s : scope) {
        count++;
        OCR_Send_Log__c logRec = (OCR_Send_Log__c) s;	
        System.debug(count.format() +  ' - Staging: ' + logRec.Title__c);
        result = SchindlerOcrStaging.launch(logRec.JsonVersionId__c);
        logRec.Result__c = result;
        if(result == 'ok') {
          logRec.Staged__c = true;
        }
        ocrUpdateList.add(logRec);
      }

      System.debug('[1] OcrBatchStaging execute: ocrUpdateList');
      System.debug(ocrUpdateList);

      Database.SaveResult[] srList = Database.update(ocrUpdateList, false);
      for (Database.SaveResult sr : srList) {
        if (!sr.isSuccess()) {
          for(Database.Error err : sr.getErrors()) {
            System.debug(err.getStatusCode() + ': ' + err.getMessage());
          }
        } else {
          String updatedId = sr.getId();
          System.debug('OcrBatchStaging execute updated Id:' + updatedId);
        }
      }

    }

    public void finish(Database.BatchableContext BC) {

      AggregateResult[] cnts = [SELECT Count(Id) Cnt FROM OCR_Send_Log__c WHERE Status__c = 'Sent' AND Staged__c = false AND Result__c != 'Errors!'];
      Integer unstagedCnt = (Integer) cnts[0].get('Cnt');

//    AuditmateUtility.decIntVal('OcrBatchCount');

//    Integer currentBatchCount = AuditmateUtility.getIntVal('OcrBatchCount');
//    if(currentBatchCount < 30 ) {
        if( unstagedCnt > 0 ) {
//        AuditmateUtility.incIntVal('OcrBatchCount');
          System.debug('OcrBatchStaging Found ' + unstagedCnt.format() + ' records in OCR_Send_Log__c requiring staging.');
          System.debug('OcrBatchStaging is now launching itself');
          Id batchInstanceId = Database.executeBatch(new OcrBatchStaging());
          System.debug('OcrBatchStaging started.  Job Id:');
          System.debug(batchInstanceId);
        } else {
          System.debug(datetime.now().format('yyyy.MM.dd HH:mm:ss z') + ' OcrBatchStaging did not see any unstaged sent records in OCR_Send_Log__c.');
        }
//    } else {
//      System.debug('OcrBatchStaging sees currentBatchCount = ' + currentBatchCount.format());
//      System.debug('OcrBatchStaging is not launching OcrBatchStaging at this time');
//    }
    }

}