force-app/main/default/objects/OCR_Send_Log__c/OCR_Send_Log__c.object-meta.xml
<CustomObject>
    <description>Log of files with their MD5 checksums that are due for OCR processing</description>
    <label>OCR Send Log</label>
    <nameField>
        <label>OCR Send Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Send Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCR_Send_Log__c/fields/Staged__c.field-meta.xml
<CustomField>
    <fullName>Staged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsent</fullName>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OcrBatchStagingHelper.cls
public without sharing class OcrBatchStagingHelper implements Schedulable {  
  // This is scheduled to run every 10 minutes.

  public void execute(SchedulableContext SC) {
   
    // Integer currentBatchCount = AuditmateUtility.getIntVal('OcrBatchCount');
    // if(currentBatchCount < 30 ) {
      AggregateResult[] cnts = [SELECT Count(Id) Cnt FROM OCR_Send_Log__c WHERE Status__c = 'Sent' AND Staged__c = false];
      Integer unstagedCnt = (Integer) cnts[0].get('Cnt');
      if( unstagedCnt > 0) {
        System.debug('OcrBatchStagingHelper Found ' + unstagedCnt.format() + ' records in OCR_Send_Log__c requiring staging.');
        Id batchInstanceId = Database.executeBatch(new OcrBatchStaging());
        System.debug('OcrBatchStagingHelper started new OcrBatchStaging.  Job Id:');
        System.debug(batchInstanceId);
      } else {
        System.debug(datetime.now().format('yyyy.MM.dd HH:mm:ss z') + ' OcrBatchStagingHelper did not see any unstaged sent record in OCR_Send_Log__c.');
      }
    // } else {
    //   System.debug('OcrBatchStagingHelper sees currentBatchCount = ' + currentBatchCount.format());
    //   System.debug('OcrBatchStagingHelper is not launching OcrBatchStaging at this time');
    // }
  }

}