force-app/main/default/objects/OCR_Send_Log__c/OCR_Send_Log__c.object-meta.xml
<CustomObject>
    <description>Log of files with their MD5 checksums that are due for OCR processing</description>
    <label>OCR Send Log</label>
    <nameField>
        <label>OCR Send Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Send Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCR_Send_Log__c/fields/JsonVersionId__c.field-meta.xml
<CustomField>
    <fullName>JsonVersionId__c</fullName>
    <label>JsonVersionId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Staged__c.field-meta.xml
<CustomField>
    <fullName>Staged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsent</fullName>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchindlerOcrStagingTest.cls
@isTest (SeeAllData=true)
public without sharing class SchindlerOcrStagingTest {

  @isTest
  public static void test1() {
    String result;
    List<OCR_Send_Log__c> unstagedList = [SELECT Id,JsonVersionId__c FROM OCR_Send_Log__c WHERE Status__c = 'Sent' AND Staged__c = false LIMIT 1];
    if(unstagedList.size() > 0) {
      OCR_Send_Log__c logRec = unstagedList[0];
      SchindlerOcrStaging.sendEmail('Test for code coverage');
      result = SchindlerOcrStaging.launch(logRec.JsonVersionId__c);
      System.debug(result);
    }
  }

}