force-app/main/default/objects/OCR_Send_Log__c/OCR_Send_Log__c.object-meta.xml
<CustomObject>
    <description>Log of files with their MD5 checksums that are due for OCR processing</description>
    <label>OCR Send Log</label>
    <nameField>
        <label>OCR Send Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Send Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCR_Send_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/JsonVersionId__c.field-meta.xml
<CustomField>
    <fullName>JsonVersionId__c</fullName>
    <label>JsonVersionId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Staged__c.field-meta.xml
<CustomField>
    <fullName>Staged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsent</fullName>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>File Title</description>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OcrBatchProcess.cls
public without sharing class OcrBatchProcess implements Database.Batchable<sObject> {

  public Database.QueryLocator start(Database.BatchableContext BC) {
    String sQuery = 'SELECT Id,Account__c,JsonVersionId__c,Staged__c,Status__c,Title__c,Processed__c FROM OCR_Send_Log__c WHERE Staged__c = true AND Processed__c = false AND Result__c != \'Errors!\' LIMIT 5';
    System.debug(sQuery);
    return Database.getQueryLocator(sQuery);
  }

  public void execute(Database.BatchableContext BC, List<sObject> scope){
    List<OCR_Send_Log__c> ocrUpdateList = new List<OCR_Send_Log__c>();
    String result;
    for (sObject s : scope) {
      OCR_Send_Log__c logRec = (OCR_Send_Log__c) s;	
      // 
      result = SchindlerOcrProcess.processStagedData(logRec.JsonVersionId__c, logRec.Account__c);
      logRec.Result__c = result;
      if(result == 'ok') {
        logRec.Processed__c = true;
      }
      System.debug(logRec.Title__c);
      System.debug(logRec.Staged__c);
      System.debug(logRec.Processed__c);
      ocrUpdateList.add(logRec);
    }
  
    Database.SaveResult[] srList = Database.update(ocrUpdateList, false);
    for (Database.SaveResult sr : srList) {
      if (!sr.isSuccess()) {
        for(Database.Error err : sr.getErrors()) {
          System.debug(err.getStatusCode() + ': ' + err.getMessage());
        }
      } else {
        String updatedId = sr.getId();
        System.debug('OCR_Send_Log updated Id:' + updatedId);
      }
    }

  }

  public void finish(Database.BatchableContext BC) {

    // Integer currentBatchCount = AuditmateUtility.getIntVal('OcrBatchCount');
    // if(currentBatchCount < 30 ) {
      AggregateResult[] cnts = [SELECT Count(Id) Cnt FROM OCR_Send_Log__c WHERE Staged__c = true AND Processed__c = false AND Result__c != 'Errors!'];
      Integer unprocessedCnt = (Integer) cnts[0].get('Cnt');
      if( unprocessedCnt > 0) {
        System.debug('OcrBatchProcess Found ' + unprocessedCnt.format() + ' records in OCR_Send_Log__c requiring to process.');
        Id batchInstanceId = Database.executeBatch(new OcrBatchProcess());
        System.debug('OcrBatchProcess started new OcrBatchProcess.  Job Id:');
        System.debug(batchInstanceId);
      } else {
        System.debug(datetime.now().format('yyyy.MM.dd HH:mm:ss z') + ' OcrBatchProcess did not see any unprocesse sent records in OCR_Send_Log__c.');
      }
    // } else {
    //   System.debug('OcrBatchProcess sees currentBatchCount = ' + currentBatchCount.format());
    //   System.debug('OcrBatchProcess is not launching OcrBatchProcess at this time');
    // }
  }

}