force-app/main/default/objects/OCR_Send_Log__c/OCR_Send_Log__c.object-meta.xml
<CustomObject>
    <description>Log of files with their MD5 checksums that are due for OCR processing</description>
    <label>OCR Send Log</label>
    <nameField>
        <label>OCR Send Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCR Send Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OCR_Send_Log__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <description>Related record Id of document that was sent to OCR Api</description>
    <label>ContentVersionId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Resend__c.field-meta.xml
<CustomField>
    <fullName>Resend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCR_Send_Log__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>File Title</description>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OcrSchedulerTest.cls
@isTest (SeeAllData=true)
private class OcrSchedulerTest {

  // This proved to be too hard to figure out how to use with test data, so it needs an email with an attachment that has not been sent to OCR. 
  @isTest
  private static void test1() {
    List<OCR_Send_Log__c> sendList = [SELECT ContentVersionId__c,Id,Resend__c,Title__c FROM OCR_Send_Log__c WHERE Title__C LIKE '%Pdf' LIMIT 1];
  
    if(sendList.size() == 1) {
      sendList[0].Resend__c = true; // Ensure a file can be sent.
      Update sendList;
      OcrScheduler.OcrSchedule(); 
    }
  }

}